import { useState } from "react";

export interface CategoryOptions {
  key: string;
  emoji: string;
  name: string;
  items: string[];
  image?: string;
  background?: string;
}

export const categories: CategoryOptions[] = [
  {
    key: "ia",
    emoji: "✨",
    items: [],
    name: "Personalizado",
    background: "#801040",
    image: require("@/assets/images/modules/ai.png"),
  },
  {
    key: "famosos-mundiais",
    emoji: "🌍",
    name: "Famosos Mundiais",
    image: require("@/assets/images/modules/famosos-mundiais.png"),
    background: "#34d214",
    items: [
      // Categoria: Atores e Atrizes
      "Leonardo DiCaprio",
      "Tom Hanks",
      "Denzel Washington",
      "Morgan Freeman",
      "Will Smith",
      "Robert Downey Jr.",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Jennifer Lawrence",
      "Angelina Jolie",
      "Meryl Streep",
      "Johnny Depp",
      "Brad Pitt",
      "Emma Stone",
      "Natalie Portman",
      "Anne Hathaway",
      "Keanu Reeves",
      "Julia Roberts",
      "Ryan Reynolds",
      "Zendaya",

      // Categoria: Cantores e Cantoras
      "Michael Jackson",
      "Beyoncé",
      "Elvis Presley",
      "Madonna",
      "Rihanna",
      "Shakira",
      "Justin Bieber",
      "Adele",
      "Taylor Swift",
      "Lady Gaga",
      "Bruno Mars",
      "The Weeknd",
      "Ed Sheeran",
      "Katy Perry",
      "Whitney Houston",
      "Bob Marley",
      "Freddie Mercury",
      "Drake",
      "Eminem",
      "Dua Lipa",

      // Categoria: Esportistas
      "Pelé",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Michael Jordan",
      "Serena Williams",
      "Lewis Hamilton",
      "Usain Bolt",
      "Simone Biles",
      "Roger Federer",
      "Neymar",
      "LeBron James",
      "Tom Brady",
      "Diego Maradona",
      "Rafael Nadal",
      "Novak Djokovic",
      "Ayrton Senna",
      "Tiger Woods",
      "Ronaldinho Gaúcho",
      "Marta",
      "Kylian Mbappé",

      // Categoria: Históricos
      "Albert Einstein",
      "Isaac Newton",
      "Marie Curie",
      "Galileu Galilei",
      "Charles Darwin",
      "Martin Luther King Jr.",
      "Mahatma Gandhi",
      "Nelson Mandela",
      "Abraham Lincoln",
      "Winston Churchill",
      "Barack Obama",
      "George Washington",
      "Cleópatra",
      "Napoleão Bonaparte",
      "Rainha Elizabeth II",
      "Joana d'Arc",
      "Leonardo da Vinci",
      "Sócrates",
      "Platão",
      "Alexandre, o Grande",

      // Categoria: Celebridades e Influencers
      "Kim Kardashian",
      "Kylie Jenner",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Charli D'Amelio",
      "Khaby Lame",
      "MrBeast",
      "Logan Paul",
      "Jake Paul",
      "PewDiePie",
      "Neymar",
      "Selena Gomez",
      "Zendaya",
      "Millie Bobby Brown",
      "Dwayne Johnson",
      "Billie Eilish",
      "Doja Cat",
      "Bad Bunny",
      "Sabrina Carpenter",
      "James Charles",

      // Categoria: Líderes e Empresários
      "Steve Jobs",
      "Bill Gates",
      "Elon Musk",
      "Mark Zuckerberg",
      "Jeff Bezos",
      "Warren Buffett",
      "Barack Obama",
      "Angela Merkel",
      "Oprah Winfrey",
      "Jacinda Ardern",
      "Xi Jinping",
      "Vladimir Putin",
      "Joe Biden",
      "Donald Trump",
      "Emmanuel Macron",
      "Luiz Inácio Lula da Silva",
      "Jair Bolsonaro",
      "Papa Francisco",
      "Greta Thunberg",
      "Malala Yousafzai",
    ],
  },
  {
    key: "carros",
    emoji: "🚗",
    name: "Carros",
    background: "#FF5733",
    image: require("@/assets/images/modules/carros.png"),
    items: [
      // Marcas: Chevrolet
      "Chevrolet Onix",
      "Chevrolet Onix Plus",
      "Chevrolet Tracker",
      "Chevrolet Spin",
      "Chevrolet Cruze",
      "Chevrolet Cruze Sport6",
      "Chevrolet S10",
      "Chevrolet Trailblazer",
      "Chevrolet Montana",
      "Chevrolet Equinox",

      // Marcas: Volkswagen
      "Volkswagen Gol",
      "Volkswagen Voyage",
      "Volkswagen Polo",
      "Volkswagen Virtus",
      "Volkswagen T-Cross",
      "Volkswagen Nivus",
      "Volkswagen Taos",
      "Volkswagen Amarok",
      "Volkswagen Tiguan Allspace",
      "Volkswagen Saveiro",

      // Marcas: Fiat
      "Fiat Mobi",
      "Fiat Argo",
      "Fiat Cronos",
      "Fiat Pulse",
      "Fiat Fastback",
      "Fiat Toro",
      "Fiat Strada",
      "Fiat Fiorino",
      "Fiat Doblò",
      "Fiat Ducato",

      // Marcas: Hyundai
      "Hyundai HB20",
      "Hyundai HB20S",
      "Hyundai Creta",
      "Hyundai Tucson",
      "Hyundai Santa Fe",
      "Hyundai Elantra",
      "Hyundai i30",

      // Marcas: Toyota
      "Toyota Corolla",
      "Toyota Corolla Cross",
      "Toyota Hilux",
      "Toyota SW4",
      "Toyota Yaris",
      "Toyota Yaris Sedan",
      "Toyota Camry",
      "Toyota RAV4",
      "Toyota Prius",

      // Marcas: Honda
      "Honda City",
      "Honda City Hatchback",
      "Honda HR-V",
      "Honda WR-V",
      "Honda Civic",
      "Honda Fit",
      "Honda CR-V",

      // Marcas: Renault
      "Renault Kwid",
      "Renault Sandero",
      "Renault Logan",
      "Renault Duster",
      "Renault Captur",
      "Renault Oroch",
      "Renault Master",

      // Marcas: Nissan
      "Nissan March",
      "Nissan Versa",
      "Nissan Kicks",
      "Nissan Sentra",
      "Nissan Frontier",

      // Marcas: Jeep
      "Jeep Renegade",
      "Jeep Compass",
      "Jeep Commander",
      "Jeep Wrangler",
      "Jeep Grand Cherokee",

      // Marcas: Ford
      "Ford Ranger",
      "Ford Territory",
      "Ford Bronco Sport",
      "Ford Edge",
      "Ford Mustang Mach 1",

      // Marcas: Peugeot
      "Peugeot 208",
      "Peugeot 2008",
      "Peugeot 3008",
      "Peugeot 5008",
      "Peugeot Partner",

      // Marcas: Citroën
      "Citroën C3",
      "Citroën C4 Cactus",
      "Citroën Jumpy",
      "Citroën Berlingo",
      "Citroën Aircross",

      // Marcas: Kia
      "Kia Picanto",
      "Kia Rio",
      "Kia Cerato",
      "Kia Sportage",
      "Kia Sorento",
      "Kia Carnival",

      // Marcas: Mitsubishi
      "Mitsubishi L200 Triton",
      "Mitsubishi Pajero Sport",
      "Mitsubishi Eclipse Cross",
      "Mitsubishi Outlander",
      "Mitsubishi ASX",

      // Marcas: Suzuki
      "Suzuki Jimny",
      "Suzuki Jimny Sierra",
      "Suzuki Vitara",
      "Suzuki Swift",

      // Marcas: BMW
      "BMW Série 1",
      "BMW Série 2",
      "BMW Série 3",
      "BMW Série 5",
      "BMW X1",
      "BMW X2",
      "BMW X3",
      "BMW X4",
      "BMW X5",
      "BMW X6",
      "BMW Z4",

      // Marcas: Mercedes-Benz
      "Mercedes-Benz Classe A",
      "Mercedes-Benz Classe C",
      "Mercedes-Benz Classe E",
      "Mercedes-Benz GLA",
      "Mercedes-Benz GLB",
      "Mercedes-Benz GLC",
      "Mercedes-Benz GLE",
      "Mercedes-Benz GLS",

      // Marcas: Audi
      "Audi A3",
      "Audi A4",
      "Audi A5",
      "Audi A6",
      "Audi Q3",
      "Audi Q5",
      "Audi Q7",
      "Audi Q8",
      "Audi e-tron",

      // Marcas: Volvo
      "Volvo XC40",
      "Volvo XC60",
      "Volvo XC90",
      "Volvo S60",
      "Volvo V60",

      // Marcas: Jaguar
      "Jaguar E-Pace",
      "Jaguar F-Pace",
      "Jaguar F-Type",
      "Jaguar I-Pace",

      // Marcas: Land Rover
      "Land Rover Defender",
      "Land Rover Discovery",
      "Land Rover Discovery Sport",
      "Land Rover Range Rover Evoque",
      "Land Rover Range Rover Velar",
      "Land Rover Range Rover Sport",

      // Marcas: Porsche
      "Porsche 911",
      "Porsche Taycan",
      "Porsche Panamera",
      "Porsche Macan",
      "Porsche Cayenne",

      // Marcas: Tesla
      "Tesla Model 3",
      "Tesla Model Y",
      "Tesla Model S",
      "Tesla Model X",

      // Marcas: Lexus
      "Lexus UX",
      "Lexus NX",
      "Lexus RX",
      "Lexus ES",
      "Lexus LS",

      // Marcas: Chery
      "Chery Tiggo 2",
      "Chery Tiggo 5X",
      "Chery Tiggo 7",
      "Chery Tiggo 8",
      "Chery Arrizo 6",

      // Outros
      "Subaru Outback",
      "Subaru Forester",
      "Subaru XV",
      "Mini Cooper",
      "Mini Cooper Countryman",
      "Maserati Ghibli",
      "Maserati Levante",
      "Ferrari Portofino",
      "Ferrari SF90 Stradale",
      "Lamborghini Huracán",
      "Lamborghini Urus",
      "Rolls-Royce Ghost",
      "Rolls-Royce Cullinan",
      "Bentley Continental GT",
      "Bentley Bentayga",
      "Pagani Huayra",
      "Koenigsegg Jesko",
      "McLaren 720S",
      "McLaren Artura",
    ],
  },
  {
    key: "frutas",
    emoji: "🍎",
    name: "Frutas",
    background: "#6B5B95",
    image: require("@/assets/images/modules/frutas.png"),
    items: [
      // Frutas do Dia a Dia
      "Banana",
      "Maçã",
      "Laranja",
      "Uva",
      "Pera",
      "Morango",
      "Mamão",
      "Abacaxi",
      "Melancia",
      "Melão",

      // Frutas Tropicais e Exóticas
      "Manga",
      "Maracujá",
      "Goiaba",
      "Caju",
      "Acerola",
      "Pitanga",
      "Graviola",
      "Jabuticaba",
      "Cupuaçu",
      "Carambola",

      // Frutas Vermelhas e Pequenas
      "Cereja",
      "Framboesa",
      "Mirtilo",
      "Amora",
      "Groselha",
      "Physalis",
      "Uva passa",
      "Cranberry",
      "Bacupari",

      // Frutas Cítricas e Azedinhas
      "Limão",
      "Lima",
      "Tangerina",
      "Mexerica",
      "Bergamota",
      "Toranja",
      "Ponkan",
      "Kumquat",
      "Laranja-lima",
      "Limão-cravo",

      // Frutas Doces e Cremosas
      "Figo",
      "Damasco",
      "Caqui",
      "Nêspera",
      "Ameixa",
      "Kiwi",
      "Romã",
      "Tamarindo",
      "Nectarina",
      "Coco",

      // Frutas Grandes e Suculentas
      "Jaca",
      "Abacate",
      "Pitaia",
      "Mangostão",
      "Pêssego",
      "Rambutan",
      "Lichia",
      "Sapoti",
      "Jenipapo",

      // Frutas Menos Conhecidas, Mas Fáceis de Lembrar
      "Cambuci",
      "Pequi",
      "Umbu",
      "Seriguela",
      "Ingá",
      "Araçá",
      "Murici",
      "Buriti",
      "Cambucá",

      // Frutas de Diferentes Partes do Mundo
      "Fruta-do-conde",
      "Mamoncillo",
      "Chirimoya",
      "Akebi",
      "Marula",
      "Noni",
      "Longan",
      "Mangaba",
      "Abiu",

      // Frutas de Cores Diferentes
      "Maçã-verde",
      "Uva-verde",
      "Morango-branco",
      "Pêssego-roxo",
      "Manga-palmer",
      "Melancia-amarela",
      "Ameixa-verde",
      "Goiaba-vermelha",
      "Figo-roxo",
      "Pitaia-amarela",

      // Frutas Que Crescem no Quintal
      "Pitomba",
      "Siriguela",
      "Amora-do-mato",
      "Ingá-mirim",
      "Uvaia",
      "Araticum",
      "Bacuri",
      "Cabeludinha",
      "Grumixama",
    ],
  },
  {
    key: "filmes",
    emoji: "🎥",
    name: "Filmes",
    background: "#87CEEB",
    image: require("@/assets/images/modules/filmes.png"),
    items: [
      "A Origem",
      "Titanic",
      "Avatar",
      "O Poderoso Chefão",
      "Coringa",
      "Pulp Fiction",
      "Clube da Luta",
      "Os Bons Companheiros",
      "O Senhor dos Anéis: A Sociedade do Anel",
      "O Senhor dos Anéis: As Duas Torres",
      "O Senhor dos Anéis: O Retorno do Rei",
      "Harry Potter e a Pedra Filosofal",
      "Harry Potter e a Câmara Secreta",
      "Harry Potter e o Prisioneiro de Azkaban",
      "Harry Potter e o Cálice de Fogo",
      "Harry Potter e a Ordem da Fênix",
      "Harry Potter e o Enigma do Príncipe",
      "Harry Potter e as Relíquias da Morte - Parte 1",
      "Harry Potter e as Relíquias da Morte - Parte 2",
      "Star Wars: Uma Nova Esperança",
      "Star Wars: O Império Contra-Ataca",
      "Star Wars: O Retorno de Jedi",
      "Star Wars: A Ameaça Fantasma",
      "Star Wars: O Ataque dos Clones",
      "Star Wars: A Vingança dos Sith",
      "Star Wars: O Despertar da Força",
      "Star Wars: Os Últimos Jedi",
      "Star Wars: A Ascensão Skywalker",
      "Homem de Ferro",
      "Homem de Ferro 2",
      "Homem de Ferro 3",
      "Os Vingadores",
      "Vingadores: Era de Ultron",
      "Vingadores: Guerra Infinita",
      "Vingadores: Ultimato",
      "Capitão América: O Primeiro Vingador",
      "Capitão América: O Soldado Invernal",
      "Capitão América: Guerra Civil",
      "Thor",
      "Thor: O Mundo Sombrio",
      "Thor: Ragnarok",
      "Thor: Amor e Trovão",
      "Pantera Negra",
      "Pantera Negra: Wakanda Para Sempre",
      "Doutor Estranho",
      "Doutor Estranho no Multiverso da Loucura",
      "Guardiões da Galáxia",
      "Guardiões da Galáxia Vol. 2",
      "Homem-Aranha: De Volta ao Lar",
      "Homem-Aranha: Longe de Casa",
      "Homem-Aranha: Sem Volta Para Casa",
      "Batman: O Cavaleiro das Trevas",
      "Batman Begins",
      "Batman: O Cavaleiro das Trevas Ressurge",
      "O Homem de Aço",
      "Liga da Justiça",
      "Liga da Justiça de Zack Snyder",
      "Mulher-Maravilha",
      "Mulher-Maravilha 1984",
      "Aquaman",
      "Shazam!",
      "Adão Negro",
      "Esquadrão Suicida",
      "Aves de Rapina",
      "O Esquadrão Suicida",
      "Matrix",
      "Matrix Reloaded",
      "Matrix Revolutions",
      "Matrix Resurrections",
      "O Exterminador do Futuro",
      "O Exterminador do Futuro 2: O Julgamento Final",
      "O Exterminador do Futuro 3: A Rebelião das Máquinas",
      "O Exterminador do Futuro: Gênesis",
      "O Exterminador do Futuro: Destino Sombrio",
      "De Volta para o Futuro",
      "De Volta para o Futuro Parte II",
      "De Volta para o Futuro Parte III",
      "Jurassic Park: O Parque dos Dinossauros",
      "O Mundo Perdido: Jurassic Park",
      "Jurassic Park III",
      "Jurassic World",
      "Jurassic World: Reino Ameaçado",
      "Jurassic World: Domínio",
      "O Rei Leão",
      "Aladdin",
      "A Bela e a Fera",
      "Cinderela",
      "Mulan",
      "A Pequena Sereia",
      "Frozen: Uma Aventura Congelante",
      "Frozen II",
      "Enrolados",
      "Valente",
      "Ratatouille",
      "Toy Story",
      "Toy Story 2",
      "Toy Story 3",
      "Toy Story 4",
      "Monstros S.A.",
      "Universidade Monstros",
      "Procurando Nemo",
      "Procurando Dory",
      "Os Incríveis",
      "Os Incríveis 2",
      "Vida de Inseto",
      "Divertida Mente",
      "Carros",
      "Carros 2",
      "Carros 3",
      "A Era do Gelo",
      "A Era do Gelo 2",
      "A Era do Gelo 3",
      "Shrek",
      "Shrek 2",
      "Shrek Terceiro",
      "Shrek Para Sempre",
      "Kung Fu Panda",
      "Kung Fu Panda 2",
      "Kung Fu Panda 3",
      "Como Treinar o Seu Dragão",
      "Como Treinar o Seu Dragão 2",
      "Como Treinar o Seu Dragão 3",
      "Madagascar",
      "Madagascar 2: A Grande Escapada",
      "Madagascar 3: Os Procurados",
      "Os Pinguins de Madagascar",
      "Minions",
      "Meu Malvado Favorito",
      "Meu Malvado Favorito 2",
      "Meu Malvado Favorito 3",
      "Coraline e o Mundo Secreto",
      "Kubo e as Cordas Mágicas",
      "ParaNorman",
      "O Estranho Mundo de Jack",
      "A Noiva Cadáver",
      "Frankenweenie",
      "A Lenda do Cavaleiro Sem Cabeça",
      "Drácula de Bram Stoker",
      "Van Helsing: O Caçador de Monstros",
      "O Lobisomem",
      "A Múmia",
      "A Múmia Returns",
      "A Múmia: Tumba do Imperador Dragão",
      "Piratas do Caribe: A Maldição do Pérola Negra",
      "Piratas do Caribe: O Baú da Morte",
      "Piratas do Caribe: No Fim do Mundo",
      "Piratas do Caribe: Navegando em Águas Misteriosas",
      "Piratas do Caribe: A Vingança de Salazar",
      "007 - Cassino Royale",
      "007 - Quantum of Solace",
      "007 - Operação Skyfall",
      "007 - Contra Spectre",
      "007 - Sem Tempo para Morrer",
      "Missão: Impossível",
      "Missão: Impossível 2",
      "Missão: Impossível 3",
      "Missão: Impossível - Protocolo Fantasma",
      "Missão: Impossível - Nação Secreta",
      "Missão: Impossível - Efeito Fallout",
      "Top Gun",
      "Top Gun: Maverick",
      "O Grande Gatsby",
      "Forrest Gump: O Contador de Histórias",
      "A Lista de Schindler",
      "À Espera de um Milagre",
      "O Pianista",
      "12 Anos de Escravidão",
      "O Jogo da Imitação",
      "A Teoria de Tudo",
      "O Discurso do Rei",
      "Bohemian Rhapsody",
      "Rocketman",
      "Elvis",
      "Os Miseráveis",
      "Cats",
      "Chicago",
      "Mamma Mia!",
      "Moulin Rouge: Amor em Vermelho",
      "La La Land: Cantando Estações",
      "Nasce Uma Estrela",
      "Os Caça-Fantasmas",
      "Os Caça-Fantasmas II",
      "Caça-Fantasmas: Mais Além",
      "It: A Coisa",
      "It: Capítulo Dois",
      "Jogos Vorazes",
      "Jogos Vorazes: Em Chamas",
      "Jogos Vorazes: A Esperança - Parte 1",
      "Jogos Vorazes: A Esperança - Parte 2",
      "Divergente",
      "Insurgente",
      "Convergente",
      "Maze Runner: Correr ou Morrer",
      "Maze Runner: Prova de Fogo",
      "Maze Runner: A Cura Mortal",
      "Crepúsculo",
      "Lua Nova",
      "Eclipse",
      "Amanhecer - Parte 1",
      "Amanhecer - Parte 2",
      "Cinquenta Tons de Cinza",
      "Cinquenta Tons Mais Escuros",
      "Cinquenta Tons de Liberdade",
      "Avatar: O Caminho da Água",
      "Duna",
      "O Senhor dos Anéis: Os Anéis de Poder",
      "O Hobbit: Uma Jornada Inesperada",
      "O Hobbit: A Desolação de Smaug",
      "O Hobbit: A Batalha dos Cinco Exércitos",
      "Jumanji",
      "Jumanji: Bem-Vindo à Selva",
      "Jumanji: Próxima Fase",
      "King Kong",
      "Godzilla",
      "Godzilla vs. Kong",
      "Pacific Rim",
      "Círculo de Fogo",
      "Cloverfield: Monstro",
      "Rua Cloverfield, 10",
      "Hereditário",
      "Midsommar",
      "Um Lugar Silencioso",
      "Um Lugar Silencioso - Parte II",
      "Corra!",
      "Nós",
      "O Sexto Sentido",
      "Fragmentado",
      "Vidro",
    ],
  },
  {
    key: "animais",
    emoji: "🐾",
    name: "Animais",
    background: "#FFB6C1",
    image: require("@/assets/images/modules/animais.png"),
    items: [
      // Mamíferos
      "Leão",
      "Tigre",
      "Elefante",
      "Girafa",
      "Canguru",
      "Panda",
      "Urso Polar",
      "Urso Pardo",
      "Gorila",
      "Chimpanzé",
      "Orangotango",
      "Lêmure",
      "Macaco-prego",
      "Tamarin",
      "Bicho-preguiça",
      "Lobo",
      "Raposa",
      "Coiote",
      "Dingo",
      "Cachorro",
      "Gato",
      "Leopardo",
      "Onça-pintada",
      "Puma",
      "Pantera",
      "Hiena",
      "Gato-do-mato",
      "Gato-selvagem",
      "Lince",
      "Caracal",
      "Coelho",
      "Lebre",
      "Porco",
      "Cavalo",
      "Zebra",
      "Hipopótamo",
      "Rinoceronte",
      "Búfalo",
      "Gnu",
      "Anta",
      "Camelo",
      "Dromedário",
      "Lhama",
      "Alpaca",
      "Cabra",
      "Ovelha",
      "Boi",
      "Vaca",
      "Touro",
      "Cervo",
      "Veado",
      "Alce",
      "Rena",
      "Bicho-da-seda",
      "Tamanduá-bandeira",
      "Tamanduá-mirim",
      "Porco-espinho",
      "Tatu",
      "Capivara",
      "Paca",
      "Gambá",
      "Lontra",
      "Ariranha",
      "Foca",
      "Leão-marinho",
      "Morsa",
      "Baleia",
      "Golfinho",
      "Narval",
      "Orca",
      "Dugongo",
      "Peixe-boi",
      "Suricato",
      "Cervo-do-pantanal",
      "Coati",
      "Puma",
      "Texugo",
      "Guaxinim",
      "Rato",
      "Ratazana",
      "Esquilo",
      "Castor",
      "Hamster",
      "Chinchila",
      "Rato-canguru",
      "Hedgehog",
      "Topo",
      "Lêmure-de-cauda-anelada",
      "Mico-leão-dourado",
      "Cavalo-marinho",

      // Aves
      "Águia",
      "Falcão",
      "Gavião",
      "Coruja",
      "Pinguim",
      "Avestruz",
      "Ema",
      "Cacatua",
      "Papagaio",
      "Arara",
      "Canário",
      "Pardal",
      "Andorinha",
      "Garça",
      "Cegonha",
      "Flamingo",
      "Pato",
      "Ganso",
      "Marreco",
      "Pelicano",
      "Albatroz",
      "Gaivota",
      "Corvo",
      "Gralha",
      "Urubu",
      "Beija-flor",
      "Cardeal",
      "Jacu",
      "Mutum",
      "Curió",
      "Jacutinga",
      "Sabiá",
      "Tucano",
      "João-de-barro",
      "Bem-te-vi",
      "Condor",
      "Carcará",
      "Anu-branco",
      "Jacana",
      "Garibaldi",
      "Seriema",
      "Aracuã",
      "Martim-pescador",
      "Saíra",
      "Periquito",
      "Galo",
      "Galinha",
      "Pavão",
      "Codorna",
      "Faisão",
      "Galo-da-serra",
      "Uirapuru",
      "Saracura",
      "Irerê",
      "Maritaca",
      "Rouxinol",
      "Pomba",
      "Rola",
      "Gavião-carijó",
      "Socó",

      // Répteis
      "Jacaré",
      "Crocodilo",
      "Iguana",
      "Lagarto",
      "Camaleão",
      "Dragão-de-komodo",
      "Cobra",
      "Jiboia",
      "Piton",
      "Sucuri",
      "Cascavel",
      "Coral",
      "Cobra-cega",
      "Tartaruga",
      "Cágado",
      "Jabuti",
      "Lagartixa",
      "Gecko",
      "Cobra-d'água",
      "Serpente-marinha",
      "Jacaré-do-papo-amarelo",
      "Caimã",
      "Teiú",
      "Basilisco",
      "Monstro-de-gila",

      // Anfíbios
      "Sapo",
      "Rã",
      "Perereca",
      "Salamandra",
      "Tritão",
      "Axolote",
      "Cecília",
      "Sapo-cururu",
      "Rã-verde",
      "Sapo-de-chifre",
      "Rã-arborícola",
      "Rã-touro",
      "Salamandra-de-fogo",
      "Rã-de-vidro",
      "Rã-dardo",

      // Peixes
      "Tubarão",
      "Raia",
      "Peixe-palhaço",
      "Peixe-leão",
      "Peixe-lua",
      "Peixe-espada",
      "Peixe-serra",
      "Peixe-boi-marinho",
      "Dourado",
      "Tilápia",
      "Salmão",
      "Bacalhau",
      "Atum",
      "Cavala",
      "Sardinha",
      "Lambari",
      "Piracanjuba",
      "Tambaqui",
      "Pirarucu",
      "Bagre",
      "Arraia",
      "Enguia",
      "Peixe-gato",
      "Peixe-anjo",
      "Peixe-betta",
      "Peixe-disco",
      "Peixe-papagaio",
      "Peixe-balão",
      "Peixe-pedra",
      "Cascudo",
      "Cichlideo",
      "Peixe-voador",
      "Peixe-borboleta",
      "Cavalo-marinho",
      "Moreia",

      // Invertebrados
      "Borboleta",
      "Abelha",
      "Formiga",
      "Vespa",
      "Mosquito",
      "Mosca",
      "Libélula",
      "Joaninha",
      "Besouro",
      "Centopeia",
      "Piolho-de-cobra",
      "Barata",
      "Cupim",
      "Mariposa",
      "Bicho-pau",
      "Aranha",
      "Escorpião",
      "Carrapato",
      "Caracol",
      "Lesma",
      "Polvo",
      "Lula",
      "Estrela-do-mar",
      "Ouriço-do-mar",
      "Esponja-marinha",
      "Medusa",
      "Anêmona-do-mar",
      "Coral",
      "Lagosta",
      "Caranguejo",
      "Camarão",
      "Sirí",
      "Krill",
      "Planária",
      "Verme",
    ],
  },
  {
    key: "marcas",
    emoji: "🛍️",
    name: "Marcas",
    background: "#FF8C00",
    image: require("@/assets/images/modules/marcas.png"),
    items: [
      // Tecnologia
      "Apple",
      "Samsung",
      "Microsoft",
      "Google",
      "Amazon",
      "Sony",
      "Huawei",
      "Xiaomi",
      "LG",
      "Intel",
      "AMD",
      "NVIDIA",
      "Dell",
      "HP",
      "Lenovo",
      "Asus",
      "Acer",
      "IBM",
      "Oracle",
      "Cisco",
      "Panasonic",
      "Toshiba",
      "Philips",
      "Sharp",
      "Seagate",

      // Automóveis
      "Toyota",
      "Volkswagen",
      "Ford",
      "Honda",
      "Nissan",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Porsche",
      "Tesla",
      "Chevrolet",
      "Kia",
      "Hyundai",
      "Lamborghini",
      "Ferrari",
      "Rolls-Royce",
      "Jaguar",
      "Land Rover",
      "Volvo",
      "Subaru",
      "Mazda",
      "Mitsubishi",
      "Peugeot",
      "Renault",
      "Fiat",
      "Jeep",
      "Dodge",
      "RAM",
      "Chrysler",
      "Cadillac",
      "Bugatti",
      "McLaren",
      "Pagani",
      "Koenigsegg",
      "Aston Martin",

      // Moda e Vestuário
      "Nike",
      "Adidas",
      "Puma",
      "Reebok",
      "Under Armour",
      "Gucci",
      "Prada",
      "Louis Vuitton",
      "Chanel",
      "Hermès",
      "Versace",
      "Armani",
      "Balenciaga",
      "Dior",
      "Burberry",
      "Tommy Hilfiger",
      "Ralph Lauren",
      "Calvin Klein",
      "Lacoste",
      "Zara",
      "H&M",
      "Uniqlo",
      "Levi's",
      "Diesel",
      "Victoria's Secret",
      "Converse",
      "Vans",
      "New Balance",
      "Fila",
      "Guess",
      "Rolex",
      "Omega",
      "Tag Heuer",
      "Swatch",
      "Casio",

      // Alimentos e Bebidas
      "Coca-Cola",
      "Pepsi",
      "Nestlé",
      "Danone",
      "Kellogg's",
      "Unilever",
      "Heinz",
      "Kraft",
      "McDonald's",
      "Burger King",
      "Subway",
      "Starbucks",
      "Domino's Pizza",
      "KFC",
      "Pizza Hut",
      "Red Bull",
      "Monster",
      "Gatorade",
      "Tropicana",
      "Lipton",
      "Nescafé",
      "Lavazza",
      "Illy",
      "Godiva",
      "Hershey's",
      "Mars",
      "Ferrero Rocher",
      "Kinder",
      "Nutella",
      "Toblerone",
      "Lay's",
      "Doritos",
      "Pringles",
      "Cheetos",
      "Oreo",

      // Luxo e Joias
      "Tiffany & Co.",
      "Cartier",
      "Bvlgari",
      "Chopard",
      "Harry Winston",
      "Pandora",
      "Swarovski",
      "De Beers",
      "Graff",
      "Van Cleef & Arpels",

      // Esporte e Fitness
      "Wilson",
      "Yonex",
      "Babolat",
      "Spalding",
      "Decathlon",
      "Peloton",
      "Technogym",
      "Precor",
      "NordicTrack",
      "Concept2",

      // Móveis e Decoração
      "Ikea",
      "Tok&Stok",
      "West Elm",
      "Crate & Barrel",
      "Pottery Barn",
      "CB2",
      "Herman Miller",
      "Ashley Furniture",
      "Havertys",
      "La-Z-Boy",

      // Cosméticos e Beleza
      "L'Oréal",
      "Estée Lauder",
      "Maybelline",
      "MAC",
      "Clinique",
      "Dove",
      "Nivea",
      "Sephora",
      "Avon",
      "O Boticário",
      "Natura",
      "Chanel Beauty",
      "Fenty Beauty",
      "Kylie Cosmetics",
      "Revlon",

      // Jogos e Entretenimento
      "PlayStation",
      "Xbox",
      "Nintendo",
      "Ubisoft",
      "Electronic Arts (EA)",
      "Activision Blizzard",
      "Square Enix",
      "Capcom",
      "Bandai Namco",
      "Sega",

      // Eletrodomésticos
      "Whirlpool",
      "GE Appliances",
      "Bosch",
      "Electrolux",
      "Frigidaire",
      "KitchenAid",
      "Samsung Appliances",
      "LG Appliances",
      "Miele",
      "Sub-Zero",

      // Transporte e Logística
      "FedEx",
      "DHL",
      "UPS",
      "Uber",
      "Lyft",
      "BlaBlaCar",
      "Cabify",
      "99",
      "Bolt",
      "Grab",

      // Bancos e Finanças
      "JP Morgan",
      "Goldman Sachs",
      "Bank of America",
      "Citibank",
      "HSBC",
      "Santander",
      "BBVA",
      "Itaú",
      "Bradesco",
      "Caixa",
      "PayPal",
      "Visa",
      "Mastercard",
      "American Express",
      "Stripe",

      // Energia e Petróleo
      "Shell",
      "BP",
      "ExxonMobil",
      "Chevron",
      "TotalEnergies",
      "Petrobras",
      "Saudi Aramco",
      "Gazprom",
      "Rosneft",
      "Eni",

      // Seguros e Saúde
      "Aetna",
      "Cigna",
      "UnitedHealth",
      "Blue Cross Blue Shield",
      "Kaiser Permanente",
      "Allianz",
      "MetLife",
      "AXA",
      "Zurich",
      "Prudential",

      // Redes de Varejo
      "Walmart",
      "Target",
      "Costco",
      "Carrefour",
      "Tesco",
      "Aldi",
      "Lidl",
      "Whole Foods",
      "7-Eleven",
      "Marks & Spencer",

      // Marcas Regionais (Extras)
      "Magalu",
      "Casas Bahia",
      "Pão de Açúcar",
      "C&A",
      "Renner",
      "Lojas Americanas",
      "Via Varejo",
      "Cencosud",
      "Mercado Livre",
      "Alibaba",
      "Tencent",
      "WeChat",
      "TikTok",
      "Bytedance",
      "Huawei",
      "Rakuten",
      "SoftBank",
      "NTT DoCoMo",
      "Sony Music",
      "Universal Music",
      "Warner Music",
      "Spotify",
      "Deezer",
      "Netflix",
      "Amazon Prime Video",
      "Disney+",
      "HBO Max",
      "Paramount+",
      "Apple TV+",
      "YouTube",
    ],
  },
  {
    key: "esportes",
    emoji: "⚽",
    name: "Esportes",
    image: require("@/assets/images/modules/esportes.png"),
    background: "#32CD32",
    items: [
      // Esportes Olímpicos
      "Atletismo",
      "Natação",
      "Ginástica Artística",
      "Ginástica Rítmica",
      "Levantamento de Peso",
      "Judô",
      "Taekwondo",
      "Boxe",
      "Esgrima",
      "Tiro com Arco",
      "Hipismo",
      "Remo",
      "Canoagem",
      "Vela",
      "Triatlo",
      "Pentatlo Moderno",
      "Badminton",
      "Tênis de Mesa",
      "Tênis",
      "Vôlei",
      "Vôlei de Praia",
      "Handebol",
      "Basquete",
      "Futebol",
      "Rugby",
      "Hóquei sobre Grama",
      "Beisebol",
      "Softbol",
      "Ciclismo de Estrada",
      "Ciclismo de Pista",
      "Mountain Bike",
      "BMX",
      "Skate",
      "Surfe",
      "Golfe",
      "Tiro Esportivo",
      "Caratê",
      "Maratona Aquática",
      "Saltos Ornamentais",
      "Polo Aquático",

      // Esportes de Inverno
      "Esqui Alpino",
      "Esqui Cross-country",
      "Biathlon",
      "Saltos de Esqui",
      "Combinado Nórdico",
      "Snowboard",
      "Patinação Artística",
      "Patinação de Velocidade",
      "Curling",
      "Hóquei no Gelo",
      "Skeleton",
      "Bobsled",
      "Luge",

      // Esportes de Raquete
      "Tênis",
      "Tênis de Mesa",
      "Badminton",
      "Squash",
      "Pickleball",
      "Padel",
      "Raquebol",
      "Frontenis",

      // Esportes de Combate
      "Judô",
      "Taekwondo",
      "Boxe",
      "Caratê",
      "Jiu-Jitsu",
      "Wrestling",
      "Sumô",
      "Krav Maga",
      "Kickboxing",
      "Muay Thai",
      "Capoeira",
      "Kung Fu",
      "Aikido",
      "Hapkido",

      // Esportes Coletivos
      "Futebol",
      "Futebol Americano",
      "Futebol Australiano",
      "Rugby",
      "Hóquei sobre Grama",
      "Hóquei no Gelo",
      "Basquete",
      "Vôlei",
      "Vôlei de Praia",
      "Handebol",
      "Polo Aquático",
      "Beisebol",
      "Softbol",
      "Críquete",

      // Esportes Aquáticos
      "Natação",
      "Polo Aquático",
      "Saltos Ornamentais",
      "Maratona Aquática",
      "Surfe",
      "Windsurf",
      "Kitesurf",
      "Bodyboard",
      "Canoagem Slalom",
      "Canoagem Velocidade",
      "Remo",
      "Vela",
      "Pesca Esportiva",

      // Esportes de Velocidade
      "Atletismo (100m, 200m, 400m)",
      "Corrida de Rua",
      "Maratona",
      "Ciclismo de Estrada",
      "Ciclismo de Pista",
      "Mountain Bike",
      "BMX",
      "Motocross",
      "Automobilismo",
      "Kart",
      "Drag Racing",
      "Patinação de Velocidade",

      // Esportes Radicais
      "Skate",
      "Bungee Jumping",
      "Paraquedismo",
      "Wingsuit",
      "Base Jumping",
      "Escalada",
      "Rapel",
      "Parkour",
      "Slackline",
      "Mountainboarding",
      "Caving",
      "Zorbing",
      "Kitesurf",
      "Rafting",
      "Downhill",

      // Esportes de Precisão
      "Golfe",
      "Tiro Esportivo",
      "Tiro com Arco",
      "Boliche",
      "Sinuca",
      "Dardos",
      "Bocha",
      "Petanca",
      "Croquet",

      // Esportes com Bola
      "Futebol",
      "Basquete",
      "Vôlei",
      "Handebol",
      "Tênis",
      "Tênis de Mesa",
      "Beisebol",
      "Softbol",
      "Críquete",
      "Polo Aquático",
      "Squash",
      "Padel",
      "Raquebol",
      "Pelota Basca",

      // Esportes e Atividades ao Ar Livre
      "Caminhadas",
      "Corrida",
      "Escalada",
      "Rapel",
      "Observação de Pássaros",
      "Montanhismo",
      "Ciclismo",
      "Trilhas de Mountain Bike",
      "Arborismo",
      "Canoagem",

      // Esportes Tradicionais e Regionais
      "Lacrosse",
      "Hurling",
      "Kabaddi",
      "Sepaktakraw",
      "Pesäpallo",
      "Gaelic Football",
      "Shinty",
      "Polo",
      "Chukker",
      "Bocha",
      "Petanca",
      "Corfebol",

      // Esportes Virtuais
      "E-sports (League of Legends, Dota 2, CS:GO, Valorant)",
      "Simuladores de Corrida",
      "FIFA",
      "NBA 2K",
      "Fortnite",
      "PUBG",
      "Call of Duty",
      "Overwatch",
      "Minecraft",

      // Outros Esportes
      "Crossfit",
      "Triatlo",
      "Pentatlo Moderno",
      "Enduro",
      "Cavalaria",
      "Esgrima",
      "Pentatlo Militar",
      "Corrida de Cavalos",
      "Turfe",
      "Ciclismo Indoor",
      "Frescobol",
      "Beach Tennis",
      "Floorball",
      "Roller Derby",
      "Ultimate Frisbee",
      "Xadrez",
      "Damas",
      "Dominó",
      "Gamão",
      "Bridge",
      "Pole Dance Esportivo",
      "Ginástica de Trampolim",
      "Patinação Artística",
      "Patinação no Gelo",
      "Cheerleading",
      "Aeróbica Esportiva",
      "Ginástica Acrobática",
    ],
  },
  {
    key: "super-herois",
    emoji: "🦸",
    name: "Super-Heróis",
    background: "#FFD700",
    image: require("@/assets/images/modules/super-herois.png"),
    items: [
      // Heróis da DC Comics
      "Superman",
      "Batman",
      "Mulher-Maravilha",
      "Flash",
      "Lanterna Verde",
      "Aquaman",
      "Ciborgue",
      "Shazam",
      "Arqueiro Verde",
      "Caçador de Marte",
      "Zatanna",
      "Constantine",
      "Canário Negro",
      "Batgirl",
      "Supergirl",
      "Robin",
      "Nightwing",
      "Raio Negro",
      "Hawkman",
      "Hawkgirl",
      "Senhor Destino",
      "Mulher-Gavião",
      "Caçadora",
      "Katana",
      "Capitão Átomo",
      "Homem-Borracha",
      "Questão",
      "Fogo",
      "Gelo",
      "Eléktron",
      "Azrael",
      "Donna Troy",
      "Jessica Cruz",
      "Kyle Rayner",
      "Guy Gardner",
      "Jay Garrick",
      "Wally West",
      "Jon Kent",
      "Damian Wayne",
      "Barbara Gordon",
      "Oráculo",
      "Vixen",
      "Estelar",
      "Ravena",
      "Mutano",
      "Monstro do Pântano",
      "Senhor Milagre",
      "Grande Barda",
      "Etrigan, o Demônio",
      "Lobo",
      "Adam Strange",
      "Bumblebee",
      "Corte das Corujas",
      "Doutora Luz",

      // Heróis da Marvel Comics
      "Homem de Ferro",
      "Capitão América",
      "Thor",
      "Hulk",
      "Viúva Negra",
      "Gavião Arqueiro",
      "Homem-Aranha",
      "Pantera Negra",
      "Doutor Estranho",
      "Wolverine",
      "Deadpool",
      "Jean Grey",
      "Ciclope",
      "Tempestade",
      "Noturno",
      "Vampira",
      "Colossus",
      "Homem de Gelo",
      "Fera",
      "Kitty Pryde",
      "Gambit",
      "Professor Xavier",
      "Feiticeira Escarlate",
      "Visão",
      "Mercúrio",
      "Senhor das Estrelas",
      "Gamora",
      "Rocket Raccoon",
      "Groot",
      "Drax, o Destruidor",
      "Capitã Marvel",
      "Homem-Formiga",
      "Vespa",
      "Shang-Chi",
      "Punho de Ferro",
      "Luke Cage",
      "Demolidor",
      "Jessica Jones",
      "Motoqueiro Fantasma",
      "Blade",
      "Elektra",
      "Justiceiro",
      "Namor",
      "Nova",
      "Adam Warlock",
      "Vigia",
      "Surfista Prateado",
      "Vigia Uatu",
      "Hércules",
      "Hulk Vermelho",
      "Hulkling",
      "Patriota de Ferro",
      "Riri Williams",
      "Moon Knight",
      "She-Hulk",
      "Dinamo Escarlate",
      "Sersi",
      "Ikaris",
      "Druig",
      "Phastos",
      "Makkari",
      "Thena",
      "Ajax",
      "Sprite",

      // Heróis de Outras Editoras
      "Hellboy",
      "Spawn",
      "Invincible",
      "Omni-Man",
      "Atom Eve",
      "Rex Splode",
      "Allen, o Alien",
      "The Tick",
      "Ben 10",
      "He-Man",
      "She-Ra",
      "Lion-O",
      "Thundercats",
      "Cheetara",
      "Panthro",
      "Tygra",
      "Silverhawks",
      "Starfire",
      "Samurai Jack",
      "Powerpuff Girls",
      "Dexter",
      "Space Ghost",
      "Birdman",
      "Mighty Mouse",
      "Underdog",

      // Heróis de Séries e Filmes
      "Buffy, a Caça-Vampiros",
      "Angel",
      "Hancock",
      "Frozone",
      "Os Incríveis",
      "Senhor Incrível",
      "Mulher-Elástica",
      "Violet Parr",
      "Dash Parr",
      "Zeze Parr",
      "Big Hero 6",
      "Baymax",
      "Hiro Hamada",
      "Wasabi",
      "Fred",
      "Go Go Tomago",
      "Yokai",

      // Heróis dos Animes
      "Goku",
      "Vegeta",
      "Naruto",
      "Sasuke",
      "Ichigo Kurosaki",
      "Luffy",
      "Zoro",
      "Sanji",
      "Nami",
      "Usopp",
      "Deku",
      "All Might",
      "Bakugo",
      "Shoto Todoroki",
      "Erza Scarlet",
      "Natsu Dragneel",
      "Gray Fullbuster",
      "Lucy Heartfilia",
      "Kirito",
      "Asuna",

      // Heróis de Jogos
      "Master Chief",
      "Lara Croft",
      "Geralt de Rivia",
      "Aloy",
      "Kratos",
      "Joel",
      "Ellie",
      "Link",
      "Zelda",
      "Samus Aran",
      "Cloud Strife",
      "Sephiroth",
      "Tifa Lockhart",
      "Barret Wallace",
      "Aerith Gainsborough",
      "Dante",
      "Nero",
      "Bayonetta",
      "Sonic",
      "Mega Man",
      "Mario",
      "Luigi",
      "Peach",
      "Bowser",
      "Yoshi",
      "Donkey Kong",
      "Diddy Kong",
      "Kirby",
      "Fox McCloud",
      "Captain Falcon",

      // Heróis Regionais e Outros
      "Zorro",
      "El Chapulín Colorado",
      "Ultraman",
      "Kamen Rider",
      "Super Sentai",
      "Power Rangers",
      "Capitão Planeta",
      "Samurai Flamenco",
      "Condor Azul",
      "Tormenta",
      "Capitão Feijão",
      "Lampião Verde",
      "Mulher Cascuda",
      "Barão Capivara",
      "Vigilante Noturno",
    ],
  },
  {
    key: "disney",
    emoji: "🏰",
    name: "Disney",
    background: "#FF69B4",
    image: require("@/assets/images/modules/disney.png"),
    items: [
      // Clássicos da Disney
      "Mickey Mouse",
      "Minnie Mouse",
      "Pato Donald",
      "Pateta",
      "Pluto",
      "Daisy Duck",
      "Tio Patinhas",
      "Zé Carioca",
      "Clarabela",
      "Horácio",
      "João Bafo-de-Onça",
      "Magali",
      "Maga Patalójika",
      "Professor Pardal",
      "Vovó Donalda",

      // Princesas da Disney
      "Branca de Neve",
      "Cinderela",
      "Aurora",
      "Ariel",
      "Bela",
      "Jasmine",
      "Pocahontas",
      "Mulan",
      "Tiana",
      "Rapunzel",
      "Anna",
      "Elsa",
      "Moana",
      "Merida",

      // Filmes da Disney
      "Simba",
      "Nala",
      "Mufasa",
      "Scar",
      "Timon",
      "Pumba",
      "Zazu",
      "Rafiki",
      "Sarabi",
      "Kovu",
      "Bambi",
      "Tambor",
      "Flor",
      "Faline",
      "Dumbo",
      "Timóteo",
      "Cinderela",
      "Fada Madrinha",
      "Lady Tremaine",
      "Drizella",
      "Anastasia",
      "Príncipe Encantado",
      "Jac e Gus",
      "Aurora",
      "Malévola",
      "Rei Stefan",
      "Rainha Leah",
      "Fadas Madrinhas: Flora, Fauna e Primavera",

      // Personagens de "A Pequena Sereia"
      "Ariel",
      "Príncipe Eric",
      "Úrsula",
      "Sebastião",
      "Linguado",
      "Rei Tritão",
      "Jett e Flotsam",

      // Personagens de "A Bela e a Fera"
      "Bela",
      "Fera",
      "Gastón",
      "Lumière",
      "Horloge",
      "Madame Samovar",
      "Zip",
      "Maurice",
      "Fifi",

      // Personagens de "Aladdin"
      "Aladdin",
      "Jasmine",
      "Gênio",
      "Abu",
      "Rajah",
      "Jafar",
      "Iago",
      "Sultão",

      // Personagens de "O Rei Leão"
      "Simba",
      "Nala",
      "Mufasa",
      "Scar",
      "Timon",
      "Pumba",
      "Zazu",
      "Rafiki",

      // Personagens de "Mulan"
      "Mulan",
      "Li Shang",
      "Mushu",
      "Cri-Kee",
      "Imperador da China",
      "Shan Yu",
      "Fa Zhou",
      "Fa Li",
      "Avó Fa",

      // Personagens de "A Princesa e o Sapo"
      "Tiana",
      "Naveen",
      "Dr. Facilier",
      "Louis",
      "Ray",
      "Charlotte La Bouff",
      "Eudora",
      "Big Daddy La Bouff",

      // Personagens de "Frozen"
      "Anna",
      "Elsa",
      "Kristoff",
      "Olaf",
      "Sven",
      "Hans",
      "Oaken",
      "Pabbie",

      // Personagens de "Moana"
      "Moana",
      "Maui",
      "Te Fiti",
      "Tamatoa",
      "Hei Hei",
      "Gramma Tala",
      "Tui",
      "Sina",

      // Personagens de "Hércules"
      "Hércules",
      "Megara",
      "Hades",
      "Filoctetes",
      "Pegasus",
      "Zeus",
      "Hera",
      "As Moiras",
      "Pain e Panic",

      // Personagens de "Alice no País das Maravilhas"
      "Alice",
      "Rainha de Copas",
      "Coelho Branco",
      "Chapeleiro Maluco",
      "Gato de Cheshire",
      "Tweedledee e Tweedledum",
      "Lagarta Azul",

      // Personagens de "Peter Pan"
      "Peter Pan",
      "Sininho",
      "Wendy",
      "Capitão Gancho",
      "Sr. Smee",
      "Crocodilo Tic-Tac",
      "Os Meninos Perdidos",

      // Personagens de "101 Dálmatas"
      "Pongo",
      "Perdita",
      "Cruella de Vil",
      "Roger",
      "Anita",
      "Horácio",
      "Gaspar",

      // Personagens de "A Dama e o Vagabundo"
      "Lady",
      "Vagabundo",
      "Joca",
      "Caco",
      "Si e Am",
      "Querida",
      "Jim Querido",

      // Personagens de "Lilo & Stitch"
      "Lilo",
      "Stitch",
      "Nani",
      "Jumba",
      "Pleakley",
      "Cobra Bubbles",
      "Capitão Gantu",

      // Personagens de "Enrolados"
      "Rapunzel",
      "Flynn Rider",
      "Mãe Gothel",
      "Pascal",
      "Maximus",
      "Os Irmãos Stabbington",

      // Personagens de "Zootopia"
      "Judy Hopps",
      "Nick Wilde",
      "Chefe Bogo",
      "Bellwether",
      "Flash",
      "Mr. Big",
      "Finnick",

      // Personagens de "Os Incríveis"
      "Senhor Incrível",
      "Mulher-Elástica",
      "Violeta",
      "Flecha",
      "Zeze",
      "Gelado",
      "Edna Moda",
      "Síndrome",

      // Personagens de "Toy Story"
      "Woody",
      "Buzz Lightyear",
      "Jessie",
      "Sr. Cabeça de Batata",
      "Betty",
      "Rex",
      "Porquinho",
      "Slinky",
      "Garfinho",

      // Personagens de "Procurando Nemo"
      "Marlin",
      "Nemo",
      "Dory",
      "Bruce",
      "Crush",
      "Gill",
      "Bubbles",
      "Peach",

      // Outros Personagens da Disney
      "Winnie the Pooh",
      "Tigrão",
      "Leitão",
      "Ió",
      "Corujão",
      "Roo",
      "Kanga",
      "Heffalump",
      "Gopher",
      "Pocahontas",
      "John Smith",
      "Meeko",
      "Governor Ratcliffe",
      "Baloo",
      "Mogli",
      "Bagheera",
      "Shere Khan",
      "Kaa",
      "Dumbo",
      "Timóteo",
      "Madame Jumbo",
      "Robin Hood",
      "Marian",
      "Pequeno João",
      "Príncipe João",
      "Sir Hiss",
      "Oswald, o Coelho Sortudo",
      "Darkwing Duck",
      "Scrooge McDuck",
      "Gizmoduck",
      "DuckTales",
      "Tico",
      "Teco",
    ],
  },
  {
    key: "livros",
    emoji: "📚",
    name: "Livros",
    background: "#8A2BE2",
    image: require("@/assets/images/modules/livros.png"),
    items: [
      // Clássicos da Literatura
      "Dom Quixote - Miguel de Cervantes",
      "Orgulho e Preconceito - Jane Austen",
      "Jane Eyre - Charlotte Brontë",
      "O Morro dos Ventos Uivantes - Emily Brontë",
      "Os Miseráveis - Victor Hugo",
      "Crime e Castigo - Fiódor Dostoiévski",
      "Guerra e Paz - Liev Tolstói",
      "O Grande Gatsby - F. Scott Fitzgerald",
      "1984 - George Orwell",
      "A Revolução dos Bichos - George Orwell",
      "Admirável Mundo Novo - Aldous Huxley",
      "Moby Dick - Herman Melville",
      "Drácula - Bram Stoker",
      "Frankenstein - Mary Shelley",
      "O Retrato de Dorian Gray - Oscar Wilde",
      "Grandes Esperanças - Charles Dickens",
      "Oliver Twist - Charles Dickens",
      "David Copperfield - Charles Dickens",
      "A Letra Escarlate - Nathaniel Hawthorne",
      "A Ilha do Tesouro - Robert Louis Stevenson",

      // Literatura Brasileira
      "Dom Casmurro - Machado de Assis",
      "Memórias Póstumas de Brás Cubas - Machado de Assis",
      "O Alienista - Machado de Assis",
      "Iracema - José de Alencar",
      "O Guarani - José de Alencar",
      "Senhora - José de Alencar",
      "Grande Sertão: Veredas - Guimarães Rosa",
      "Capitães da Areia - Jorge Amado",
      "O Sítio do Pica-Pau Amarelo - Monteiro Lobato",
      "O Quinze - Rachel de Queiroz",
      "Vidas Secas - Graciliano Ramos",
      "O Auto da Compadecida - Ariano Suassuna",
      "A Moreninha - Joaquim Manuel de Macedo",
      "O Cortiço - Aluísio Azevedo",
      "Macunaíma - Mário de Andrade",

      // Ficção Científica e Fantasia
      "Duna - Frank Herbert",
      "Fundação - Isaac Asimov",
      "Eu, Robô - Isaac Asimov",
      "Neuromancer - William Gibson",
      "Snow Crash - Neal Stephenson",
      "2001: Uma Odisseia no Espaço - Arthur C. Clarke",
      "Jogador Número 1 - Ernest Cline",
      "O Homem do Castelo Alto - Philip K. Dick",
      "Androides Sonham com Ovelhas Elétricas? - Philip K. Dick",
      "Harry Potter e a Pedra Filosofal - J.K. Rowling",
      "Harry Potter e a Câmara Secreta - J.K. Rowling",
      "Harry Potter e o Prisioneiro de Azkaban - J.K. Rowling",
      "O Senhor dos Anéis: A Sociedade do Anel - J.R.R. Tolkien",
      "O Senhor dos Anéis: As Duas Torres - J.R.R. Tolkien",
      "O Senhor dos Anéis: O Retorno do Rei - J.R.R. Tolkien",
      "O Hobbit - J.R.R. Tolkien",
      "As Crônicas de Nárnia - C.S. Lewis",
      "O Leão, a Feiticeira e o Guarda-Roupa - C.S. Lewis",
      "Eragon - Christopher Paolini",
      "Percy Jackson e o Ladrão de Raios - Rick Riordan",

      // Romance e Ficção
      "O Morro dos Ventos Uivantes - Emily Brontë",
      "O Sol é para Todos - Harper Lee",
      "A Culpa é das Estrelas - John Green",
      "Se Eu Ficar - Gayle Forman",
      "A Última Música - Nicholas Sparks",
      "Querido John - Nicholas Sparks",
      "P.S. Eu Te Amo - Cecelia Ahern",
      "Um Dia - David Nicholls",
      "Cinquenta Tons de Cinza - E.L. James",
      "Orgulho e Preconceito - Jane Austen",
      "Emma - Jane Austen",
      "Persuasão - Jane Austen",
      "Razão e Sensibilidade - Jane Austen",
      "A Casa dos Espíritos - Isabel Allende",

      // Suspense e Mistério
      "O Código Da Vinci - Dan Brown",
      "Anjos e Demônios - Dan Brown",
      "Inferno - Dan Brown",
      "O Símbolo Perdido - Dan Brown",
      "A Mulher na Janela - A.J. Finn",
      "Garota Exemplar - Gillian Flynn",
      "O Silêncio dos Inocentes - Thomas Harris",
      "O Colecionador de Ossos - Jeffery Deaver",
      "Os Homens que Não Amavam as Mulheres - Stieg Larsson",
      "A Menina que Brincava com Fogo - Stieg Larsson",
      "A Rainha do Castelo de Ar - Stieg Larsson",
      "O Iluminado - Stephen King",
      "It: A Coisa - Stephen King",
      "Carrie, a Estranha - Stephen King",
      "Doutor Sono - Stephen King",

      // Distopias e Literatura Contemporânea
      "Jogos Vorazes - Suzanne Collins",
      "Em Chamas - Suzanne Collins",
      "A Esperança - Suzanne Collins",
      "Divergente - Veronica Roth",
      "Insurgente - Veronica Roth",
      "Convergente - Veronica Roth",
      "A Seleção - Kiera Cass",
      "A Elite - Kiera Cass",
      "A Escolha - Kiera Cass",

      // Não Ficção
      "Sapiens: Uma Breve História da Humanidade - Yuval Noah Harari",
      "Homo Deus - Yuval Noah Harari",
      "21 Lições para o Século 21 - Yuval Noah Harari",
      "O Poder do Hábito - Charles Duhigg",
      "Os Segredos da Mente Milionária - T. Harv Eker",
      "Pai Rico, Pai Pobre - Robert Kiyosaki",
      "A Arte da Guerra - Sun Tzu",
      "O Príncipe - Maquiavel",
      "Como Fazer Amigos e Influenciar Pessoas - Dale Carnegie",
      "Mindset: A Nova Psicologia do Sucesso - Carol S. Dweck",

      // Livros Infantis
      "O Pequeno Príncipe - Antoine de Saint-Exupéry",
      "Alice no País das Maravilhas - Lewis Carroll",
      "A Fantástica Fábrica de Chocolate - Roald Dahl",
      "Matilda - Roald Dahl",
      "O Grúfalo - Julia Donaldson",
      "Harry, o Cão Sujo - Gene Zion",
      "Pedro Coelho - Beatrix Potter",
      "O Gato de Botas - Charles Perrault",

      // Outros
      "1984 - George Orwell",
      "A Revolução dos Bichos - George Orwell",
      "Admirável Mundo Novo - Aldous Huxley",
      "A Metamorfose - Franz Kafka",
      "O Processo - Franz Kafka",
      "O Castelo - Franz Kafka",
      "Fahrenheit 451 - Ray Bradbury",
      "O Apanhador no Campo de Centeio - J.D. Salinger",
      "A Sangue Frio - Truman Capote",
      "O Nome da Rosa - Umberto Eco",
      "A Montanha Mágica - Thomas Mann",
    ],
  },
  {
    key: "profissoes",
    emoji: "💼",
    name: "Profissões",
    background: "#FF4500",
    image: require("@/assets/images/modules/profissoes.png"),
    items: [
      // Saúde e Bem-estar
      "Médico",
      "Enfermeiro",
      "Dentista",
      "Fisioterapeuta",
      "Psicólogo",
      "Nutricionista",
      "Farmacêutico",
      "Oftalmologista",
      "Pediatra",
      "Veterinário",
      "Técnico de Enfermagem",
      "Terapeuta Ocupacional",
      "Cardiologista",
      "Ortopedista",
      "Dermatologista",
      "Geriatra",
      "Ginecologista",
      "Obstetra",
      "Anestesista",
      "Psiquiatra",
      "Endocrinologista",
      "Urologista",
      "Cirurgião",
      "Fonoaudiólogo",
      "Podólogo",
      "Assistente Social",
      "Massoterapeuta",
      "Quiropraxista",
      "Homeopata",
      "Acupunturista",

      // Tecnologia e Informática
      "Desenvolvedor de Software",
      "Engenheiro de Software",
      "Analista de Sistemas",
      "Cientista de Dados",
      "Especialista em Segurança da Informação",
      "Administrador de Redes",
      "Designer de UX/UI",
      "Desenvolvedor Front-End",
      "Desenvolvedor Back-End",
      "Desenvolvedor Mobile",
      "Arquiteto de Sistemas",
      "Técnico de Informática",
      "Game Designer",
      "Analista de Suporte Técnico",
      "Programador",
      "Engenheiro de Dados",
      "Administrador de Banco de Dados",
      "Especialista em Cloud Computing",
      "Engenheiro de Machine Learning",
      "Analista de BI (Business Intelligence)",
      "Testador de Software",
      "DevOps",
      "Scrum Master",
      "Gerente de Projetos de TI",
      "Analista de SEO",
      "Especialista em Marketing Digital",
      "Engenheiro de Redes",
      "Especialista em Inteligência Artificial",
      "Arquiteto de Soluções",
      "Desenvolvedor Blockchain",

      // Educação
      "Professor de Ensino Fundamental",
      "Professor de Ensino Médio",
      "Professor Universitário",
      "Pedagogo",
      "Educador Físico",
      "Instrutor de Línguas",
      "Professor de Inglês",
      "Professor de Matemática",
      "Professor de História",
      "Professor de Geografia",
      "Professor de Física",
      "Professor de Química",
      "Professor de Biologia",
      "Professor de Artes",
      "Professor de Música",
      "Orientador Educacional",
      "Coordenador Pedagógico",
      "Tutor",
      "Instrutor de Treinamento",
      "Especialista em Educação Especial",

      // Artes e Design
      "Artista Plástico",
      "Designer Gráfico",
      "Ilustrador",
      "Fotógrafo",
      "Cinegrafista",
      "Diretor de Arte",
      "Animador 2D",
      "Animador 3D",
      "Editor de Vídeo",
      "Diretor de Fotografia",
      "Roteirista",
      "Designer de Moda",
      "Estilista",
      "Arquiteto",
      "Designer de Interiores",
      "Escultor",
      "Pintor",
      "Designer Industrial",
      "Decorador de Eventos",
      "Curador de Arte",

      // Ciências e Pesquisa
      "Biólogo",
      "Químico",
      "Físico",
      "Matemático",
      "Geógrafo",
      "Arqueólogo",
      "Historiador",
      "Antropólogo",
      "Sociólogo",
      "Cientista Político",
      "Astrônomo",
      "Geólogo",
      "Meteorologista",
      "Oceanógrafo",
      "Ecologista",
      "Pesquisador",
      "Bioquímico",
      "Geneticista",
      "Engenheiro Nuclear",
      "Engenheiro Ambiental",

      // Construção Civil
      "Engenheiro Civil",
      "Arquiteto",
      "Pedreiro",
      "Mestre de Obras",
      "Carpinteiro",
      "Eletricista",
      "Encanador",
      "Pintor de Obras",
      "Marceneiro",
      "Serralheiro",
      "Operador de Máquinas Pesadas",
      "Técnico em Construção Civil",
      "Topógrafo",
      "Soldador",
      "Técnico em Edificações",

      // Comércio e Vendas
      "Vendedor",
      "Gerente de Loja",
      "Representante Comercial",
      "Caixa",
      "Estoquista",
      "Assistente de Vendas",
      "Comprador",
      "Supervisor de Vendas",
      "Diretor Comercial",
      "Analista de E-commerce",
      "Corretor de Imóveis",
      "Corretor de Seguros",
      "Atendente de Call Center",
      "Promotor de Vendas",
      "Publicitário",

      // Administração e Negócios
      "Administrador",
      "Contador",
      "Economista",
      "Auditor",
      "Gerente Financeiro",
      "Analista de Recursos Humanos",
      "Gerente de RH",
      "Assistente Administrativo",
      "Consultor de Negócios",
      "Secretário Executivo",
      "Analista de Logística",
      "Gerente de Logística",
      "Analista de Marketing",
      "Gerente de Projetos",
      "Analista de Planejamento",
      "Gerente Geral",
      "Analista de Controle de Qualidade",
      "Especialista em Compliance",
      "Planejador Financeiro",
      "Analista de Gestão de Riscos",

      // Indústria e Produção
      "Engenheiro de Produção",
      "Técnico em Mecânica",
      "Operador de Máquinas",
      "Engenheiro Mecânico",
      "Técnico em Eletrônica",
      "Técnico em Eletrotécnica",
      "Operador de CNC",
      "Engenheiro Eletricista",
      "Engenheiro Químico",
      "Ferramenteiro",
      "Supervisor de Produção",
      "Técnico em Automação Industrial",
      "Inspetor de Qualidade",
      "Caldeireiro",
      "Montador Industrial",

      // Serviços
      "Garçom",
      "Cozinheiro",
      "Chef de Cozinha",
      "Recepcionista",
      "Camareira",
      "Motorista",
      "Motoboy",
      "Zelador",
      "Faxineiro",
      "Barman",
      "Jardineiro",
      "Piscineiro",
      "Manicure",
      "Cabeleireiro",
      "Maquiador",
      "Esteticista",
      "Cuidador de Idosos",
      "Babá",
      "Segurança",
      "Porteiro",

      // Direito e Justiça
      "Advogado",
      "Juiz",
      "Promotor de Justiça",
      "Defensor Público",
      "Escrivão",
      "Policial",
      "Delegado",
      "Investigador",
      "Perito Criminal",
      "Técnico Judiciário",
      "Procurador",
      "Mediador",
      "Assistente Jurídico",
      "Oficial de Justiça",
      "Analista Jurídico",

      // Transportes e Logística
      "Piloto de Avião",
      "Comissário de Bordo",
      "Controlador de Tráfego Aéreo",
      "Engenheiro Aeronáutico",
      "Mecânico de Aeronaves",
      "Caminhoneiro",
      "Motorista de Ônibus",
      "Taxista",
      "Condutor de Trem",
      "Agente de Carga",
      "Despachante Aduaneiro",
      "Técnico em Logística",
      "Coordenador de Frota",
      "Operador de Empilhadeira",
      "Auxiliar de Logística",

      // Agricultura e Pecuária
      "Agrônomo",
      "Veterinário",
      "Zootecnista",
      "Técnico Agrícola",
      "Pecuarista",
      "Produtor Rural",
      "Engenheiro Florestal",
      "Apicultor",
      "Silvicultor",
      "Operador de Máquinas Agrícolas",

      // Outras Profissões
      "Astronauta",
      "Militar",
      "Pastor",
      "Padre",
      "Monge",
      "Escritor",
      "Poeta",
      "Jornalista",
      "Redator",
      "Tradutor",
      "Editor",
      "Revisor",
      "Locutor",
      "Apresentador de TV",
      "YouTuber",
      "Streamer",
      "Influenciador Digital",
      "Coach",
      "Consultor de Imagem",
      "Personal Trainer",
    ],
  },
  {
    key: "flores",
    emoji: "🌸",
    name: "Flores",
    background: "#FFB6C1",
    image: require("@/assets/images/modules/flores.png"),
    items: [
      // Flores Ornamentais e Populares
      "Rosa",
      "Tulipa",
      "Girassol",
      "Lírio",
      "Orquídea",
      "Crisântemo",
      "Jasmim",
      "Lavanda",
      "Hortênsia",
      "Camélia",
      "Dália",
      "Amarílis",
      "Azaleia",
      "Cravo",
      "Peônia",
      "Gérbera",
      "Begônia",
      "Petúnia",
      "Violeta",
      "Margarida",

      // Flores Tropicais
      "Hibisco",
      "Costus",
      "Helicônia",
      "Bromélia",
      "Alpinia",
      "Ave-do-Paraíso",
      "Antúrio",
      "Bananeira Ornamental",
      "Calathea",
      "Maranta",
      "Costela-de-Adão",
      "Ixora",
      "Jasmim-Manga",
      "Canna",
      "Caesalpinia",

      // Flores Selvagens
      "Dente-de-Leão",
      "Papoula",
      "Campânula",
      "Miosótis",
      "Dedaleira",
      "Centáurea",
      "Vinca",
      "Verônica",
      "Margaridinha",
      "Anêmona",
      "Malva",
      "Trevo Florido",
      "Gerânio",
      "Agerato",
      "Cosmos",

      // Flores Medicinais
      "Camomila",
      "Calêndula",
      "Equinácea",
      "Alecrim",
      "Erva-doce",
      "Lavanda",
      "Hortelã",
      "Capim-Limão",
      "Salvia",
      "Tília",
      "Passiflora",
      "Malva Cheirosa",
      "Mil-Folhas",
      "Arruda",
      "Guaco",

      // Flores Raras
      "Flor-de-Lótus",
      "Rafflesia Arnoldii",
      "Flor-Cadáver",
      "Flor-de-Cera",
      "Flor-do-Medo",
      "Rosa Negra de Halfeti",
      "Orquídea-Fantasma",
      "Orquídea-Sapatinho",
      "Protea-Rei",
      "Jade-Vermelha",
      "Magnólia",
      "Trombeta-de-Anjo",
      "Cipó-de-São-João",
      "Flor-de-Cactus",
      "Flor-de-Maio",

      // Flores Aquáticas
      "Vitória-Régia",
      "Nenúfar",
      "Lótus",
      "Iris-d’água",
      "Alface-d’água",
      "Sagittaria",
      "Pontederia",
      "Samambaia-d’água",
      "Flor-de-Aguapé",
      "Flor-de-Lótus-Branca",

      // Rosas por Variedades
      "Rosa Vermelha",
      "Rosa Branca",
      "Rosa Amarela",
      "Rosa Cor-de-Rosa",
      "Rosa Coral",
      "Rosa Azul",
      "Rosa Negra",
      "Rosa Laranja",
      "Rosa Chá",
      "Rosa Arco-Íris",

      // Orquídeas por Variedades
      "Orquídea Phalaenopsis",
      "Orquídea Dendrobium",
      "Orquídea Cattleya",
      "Orquídea Vanda",
      "Orquídea Oncidium",
      "Orquídea Cymbidium",
      "Orquídea Vanilla",
      "Orquídea Miltonia",
      "Orquídea Ludisia",
      "Orquídea Bulbophyllum",

      // Flores Clássicas
      "Narciso",
      "Íris",
      "Freesia",
      "Jacinto",
      "Alstroemeria",
      "Lisianthus",
      "Ranúnculo",
      "Estrelícia",
      "Flor-de-Lis",
      "Flor-de-Amendoeira",
      "Flor-de-Cerejeira",
      "Flor-de-Macieira",
      "Flor-de-Pessegueiro",
      "Flor-de-Pereira",
      "Flor-de-Mangueira",

      // Flores de Jardim
      "Impatiens",
      "Zínia",
      "Calibrachoa",
      "Kalanchoe",
      "Bougainvillea",
      "Alyssum",
      "Lobélia",
      "Viola",
      "Flor-de-Mel",
      "Snapdragon",
      "Coleus",
      "Perpétua",
      "Ciclame",
      "Gladiolo",
      "Nigella",

      // Flores Alpinas
      "Edelweiss",
      "Genciana",
      "Campânula Alpina",
      "Flox Subulata",
      "Anêmona Alpina",
      "Helianthemum",
      "Aster Alpino",
      "Silene",
      "Verônica Alpina",
      "Dianthus Alpino",

      // Outras Flores
      "Flor-de-Maracujá",
      "Flor-de-Ipê",
      "Flor-de-Cajueiro",
      "Flor-de-Laranja",
      "Flor-de-Café",
      "Flor-de-Pitanga",
      "Flor-de-Jabuticaba",
      "Flor-de-Umbu",
      "Flor-de-Seriguela",
      "Flor-de-Tamarindo",
      "Flor-de-Jacarandá",
      "Flor-de-Manacá",
      "Flor-de-Pau-Brasil",
      "Flor-de-Aroeira",
      "Flor-de-Magnólia",
      "Flor-de-Ceibo",
      "Flor-de-Aroeira-Vermelha",
      "Flor-de-Cedro",
      "Flor-de-Mulungu",
      "Flor-de-Jasmim-da-Noite",
      "Flor-de-Rosmaninho",
      "Flor-de-Hibisco-Rosa",
      "Flor-de-Alfazema",
      "Flor-de-Açucena",
      "Flor-de-Lobélia",
    ],
  },
  {
    key: "objetos",
    emoji: "🎒",
    name: "Objetos do Dia a Dia",
    background: "#FFD700",
    image: require("@/assets/images/modules/objetos.png"),
    items: [
      // Objetos do Dia a Dia
      "Celular",
      "Relógio",
      "Carteira",
      "Óculos",
      "Chave",
      "Bolsa",
      "Mochila",
      "Fone de Ouvido",
      "Carregador",
      "Guarda-chuva",
      "Porta-moedas",
      "Caneta",
      "Lápis",
      "Borracha",
      "Caderno",
      "Livro",
      "Revista",
      "Jornal",
      "Bloco de Notas",
      "Agenda",
      "Cartão de Crédito",
      "Documento de Identidade",
      "Passaporte",
      "Máscara",
      "Roupas",

      // Utensílios Domésticos
      "Panela",
      "Frigideira",
      "Faca",
      "Garfo",
      "Colher",
      "Prato",
      "Copo",
      "Xícara",
      "Tigela",
      "Pote de Vidro",
      "Tábua de Corte",
      "Espremedor de Alho",
      "Ralador",
      "Abridor de Garrafa",
      "Saca-rolhas",
      "Escumadeira",
      "Espátula",
      "Concha",
      "Coador",
      "Tampa de Panela",
      "Chaleira",
      "Cafeteira",
      "Liquidificador",
      "Batedeira",
      "Panela de Pressão",
      "Aspirador de Pó",
      "Ferro de Passar",
      "Ventilador",
      "Luminária",
      "Abajur",

      // Ferramentas
      "Martelo",
      "Chave de Fenda",
      "Alicate",
      "Serrote",
      "Furadeira",
      "Parafusadeira",
      "Trena",
      "Nível",
      "Broca",
      "Plaina",
      "Esquadro",
      "Marreta",
      "Torquímetro",
      "Chave Inglesa",
      "Chave Allen",
      "Pé de Cabra",
      "Serra",
      "Cortador de Grama",
      "Tesoura de Poda",
      "Rolo de Pintura",
      "Pincel",
      "Colher de Pedreiro",
      "Espátula de Massa",
      "Disco de Corte",
      "Corta-vergalhão",

      // Eletrônicos
      "Computador",
      "Notebook",
      "Tablet",
      "Monitor",
      "Mouse",
      "Teclado",
      "Impressora",
      "Scanner",
      "Câmera Digital",
      "Drone",
      "Smartwatch",
      "Caixa de Som",
      "Controle Remoto",
      "Televisão",
      "Console de Videogame",
      "Roteador",
      "Modem",
      "Power Bank",
      "Pen Drive",
      "HD Externo",
      "Calculadora",
      "Projetor",
      "Microfone",
      "Webcam",
      "Leitor de Cartão",

      // Brinquedos e Jogos
      "Bola",
      "Boneca",
      "Carrinho de Brinquedo",
      "Cubo Mágico",
      "Urso de Pelúcia",
      "Quebra-cabeça",
      "Jogo de Tabuleiro",
      "Videogame",
      "Baralho",
      "Dominó",
      "Pião",
      "Slime",
      "Brinquedo de Construção",
      "Patinete",
      "Bicicleta",
      "Skate",
      "Patins",
      "Boliche",
      "Flauta de Plástico",
      "Balão",
      "Brinquedo de Praia",
      "Boneco de Ação",
      "Yo-Yo",
      "Jogo de Dardos",
      "Kit de Mágica",

      // Instrumentos Musicais
      "Violão",
      "Guitarra",
      "Baixo",
      "Piano",
      "Teclado Musical",
      "Bateria",
      "Flauta",
      "Violino",
      "Saxofone",
      "Clarinete",
      "Trompete",
      "Trombone",
      "Ukulele",
      "Tambor",
      "Pandeiro",
      "Cavaquinho",
      "Harmônica",
      "Bandolim",
      "Oboé",
      "Banjo",

      // Objetos de Escritório
      "Grampeador",
      "Furador de Papel",
      "Clipes",
      "Marcador de Texto",
      "Lápis de Cor",
      "Tesoura",
      "Régua",
      "Apontador",
      "Pasta de Documentos",
      "Calculadora",
      "Post-it",
      "Carimbo",
      "Envelope",
      "Lapiseira",
      "Fita Adesiva",
      "Fita Corretiva",
      "Cartucheira",
      "Porta-lápis",
      "Bloco Adesivo",
      "Caneta Marcadora",

      // Objetos de Transporte
      "Bicicleta",
      "Skate",
      "Patinete",
      "Capacete",
      "Luva de Ciclista",
      "Corrente de Bicicleta",
      "Lanterna para Bicicleta",
      "Cadeado de Bicicleta",
      "Buzina",
      "Pneu de Reposição",
      "Chave de Roda",
      "Triângulo de Sinalização",
      "Macaco Hidráulico",
      "Extintor de Incêndio",
      "Porta-malas",

      // Objetos de Decoração
      "Vaso de Planta",
      "Quadro",
      "Espelho",
      "Cortina",
      "Tapete",
      "Relógio de Parede",
      "Porta-Retrato",
      "Abajur",
      "Velas Decorativas",
      "Almofadas",
      "Estatueta",
      "Cesto de Roupas",
      "Luminária de Teto",
      "Adornos de Mesa",
      "Lareira Artificial",

      // Objetos Diversos
      "Caixa de Ferramentas",
      "Mala de Viagem",
      "Mochila Escolar",
      "Lanterna",
      "Bússola",
      "Saco de Dormir",
      "Bota de Caminhada",
      "Garrafa Térmica",
      "Cantil",
      "Binóculos",
      "Barraca de Camping",
      "Chaveiro",
      "Toalha",
      "Espelho de Bolso",
      "Estojo",
      "Flauta Doce",
      "Bandeira",
      "Sino",
      "Corrente",
      "Cinto",
      "Pente",
      "Escova de Dentes",
      "Fio Dental",
      "Saboneteira",
      "Copo Térmico",
      "Squeeze",
      "Guarda-joias",
      "Abridor de Cartas",
      "Bússola de Bolso",
      "Balança Digital",
    ],
  },
  {
    key: "harry-potter",
    emoji: "🧙",
    name: "Harry Potter",
    background: "#33a2b5",
    image: require("@/assets/images/modules/harry-potter.png"),
    items: [
      // Personagens Principais
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Alvo Dumbledore",
      "Severo Snape",
      "Voldemort",
      "Draco Malfoy",
      "Neville Longbottom",
      "Ginny Weasley",
      "Rubeus Hagrid",
      "Minerva McGonagall",
      "Sirius Black",
      "Remo Lupin",
      "Luna Lovegood",
      "Bellatrix Lestrange",
      "Lucius Malfoy",
      "Narcisa Malfoy",
      "Dobby",
      "Dolores Umbridge",
      "Fred Weasley",
      "George Weasley",
      "Arthur Weasley",
      "Molly Weasley",
      "Percy Weasley",
      "Fleur Delacour",
      "Cho Chang",
      "Cedrico Diggory",
      "Vítor Krum",
      "Pedro Pettigrew",
      "Ninfadora Tonks",

      // Feitiços
      "Expelliarmus",
      "Lumos",
      "Nox",
      "Wingardium Leviosa",
      "Alohomora",
      "Accio",
      "Expecto Patronum",
      "Avada Kedavra",
      "Crucio",
      "Imperio",
      "Obliviate",
      "Petrificus Totalus",
      "Rictusempra",
      "Stupefy",
      "Protego",
      "Sectumsempra",
      "Diffindo",
      "Legilimens",
      "Occlumens",
      "Aguamenti",
      "Reducto",
      "Incendio",
      "Muffliato",
      "Portus",
      "Engorgio",
      "Reducio",
      "Silencio",
      "Reparo",
      "Rennervate",
      "Ferula",

      // Locais Icônicos
      "Hogwarts",
      "Beco Diagonal",
      "Hogsmeade",
      "Floresta Proibida",
      "Salão Principal",
      "Casa dos Gritos",
      "Lago Negro",
      "Torre de Astronomia",
      "Salão Comunal da Grifinória",
      "Salão Comunal da Sonserina",
      "Salão Comunal da Lufa-Lufa",
      "Salão Comunal da Corvinal",
      "Aula de Poções",
      "Aula de Defesa Contra as Artes das Trevas",
      "Campo de Quadribol",
      "Toca dos Weasley",
      "Ministério da Magia",
      "Banco Gringotes",
      "Caverna do Medalhão",
      "Godric's Hollow",
      "Privet Drive",
      "Cabana de Hagrid",
      "King's Cross",
      "Cemitério de Little Hangleton",
      "Azkaban",

      // Criaturas Mágicas
      "Hipogrifo",
      "Testrálio",
      "Bicuço",
      "Dementador",
      "Elfo Doméstico",
      "Dragão",
      "Basilisco",
      "Acromântula",
      "Fênix",
      "Arraia Cega",
      "Diabretes da Cornualha",
      "Bicho-papão",
      "Cervo Patronus",
      "Lobisomem",
      "Unicórnio",
      "Grindylow",
      "Troll",
      "Nundu",
      "Kneazle",
      "Explosivins",

      // Objetos Mágicos
      "Varinha de Sabugueiro",
      "Mapa do Maroto",
      "Capa da Invisibilidade",
      "Pedra Filosofal",
      "Diadema de Ravenclaw",
      "Espelho de Ojesed",
      "Horcruxes",
      "Diário de Tom Riddle",
      "Anel de Gaunt",
      "Medalhão de Slytherin",
      "Taça de Hufflepuff",
      "Nagini",
      "Relíquias da Morte",
      "Pomo de Ouro",
      "Vassoura Nimbus 2000",
      "Vassoura Nimbus 2001",
      "Firebolt",
      "Caldeirão",
      "Pena de Aparição",
      "Pena de Fênix",
      "Pensador",
      "Bebedouro Mágico",
      "Galeões de Ouro",
      "Sicles de Prata",
      "Knuts de Bronze",
      "Chave de Portal",
      "Espelho de Dois Lados",
      "Livro Monstruoso dos Monstros",
      "Determinador",
      "Profeta Diário",
      "Relojoeiro de Poções",
      "Varinha do Harry",
      "Varinha do Voldemort",
      "Relógio dos Weasley",
      "Floo Powder",

      // Quadribol
      "Pomo de Ouro",
      "Balaço",
      "Goles",
      "Vassoura Voadora",
      "Campo de Quadribol",
      "Artilheiro",
      "Apanhador",
      "Batedor",
      "Goleiro",

      // Poções e Ingredientes
      "Poção Polissuco",
      "Poção do Amor",
      "Felix Felicis",
      "Poção do Sono",
      "Veritaserum",
      "Amortentia",
      "Essência de Ditamno",
      "Poção Wiggenweld",
      "Sangue de Dragão",
      "Olho de Tritão",
      "Cabelo de Unicórnio",
      "Asfódelo em Pó",
      "Coração de Dragão",
      "Mandrágora",
      "Besouro Triturado",
      "Raiz de Gengibre",
      "Sanguinária",
      "Escama de Dragão",
      "Pó de Lua",
      "Semente de Erumpente",

      // Professores de Hogwarts
      "Alvo Dumbledore",
      "Minerva McGonagall",
      "Severo Snape",
      "Gilderoy Lockhart",
      "Remo Lupin",
      "Dolores Umbridge",
      "Firenze",
      "Horace Slughorn",
      "Pomona Sprout",
      "Sybil Trelawney",
      "Quirinus Quirrell",
      "Rubeus Hagrid",
      "Aurora Sinistra",
      "Filius Flitwick",
      "Madame Hooch",

      // Outras Coisas do Universo
      "Chapéu Seletor",
      "Homenzinho do Tempo",
      "Retratos Mágicos",
      "Corujas",
      "Cachorro de Três Cabeças",
      "Tri-Bruxo",
      "Torneio de Feitiçaria",
      "Varinha do Dragão",
      "Escudo Protego",
      "Maroto Mapa",
      "Sapo de Chocolate",
      "Feijãozinho de Todos os Sabores",
      "Cerveja Amanteigada",
      "Suco de Abóbora",
      "Réplica de Quadribol",
    ],
  },
  {
    key: "pokemons",
    emoji: "🐉",
    name: "Pokémons 1ª geração (Kanto)",
    background: "#FF6347",
    image: require("@/assets/images/modules/pokemons.png"),
    items: [
      "Bulbasaur",
      "Ivysaur",
      "Venusaur",
      "Charmander",
      "Charmeleon",
      "Charizard",
      "Squirtle",
      "Wartortle",
      "Blastoise",
      "Caterpie",
      "Metapod",
      "Butterfree",
      "Weedle",
      "Kakuna",
      "Beedrill",
      "Pidgey",
      "Pidgeotto",
      "Pidgeot",
      "Rattata",
      "Raticate",
      "Spearow",
      "Fearow",
      "Ekans",
      "Arbok",
      "Pikachu",
      "Raichu",
      "Sandshrew",
      "Sandslash",
      "Nidoran♀",
      "Nidorina",
      "Nidoqueen",
      "Nidoran♂",
      "Nidorino",
      "Nidoking",
      "Clefairy",
      "Clefable",
      "Vulpix",
      "Ninetales",
      "Jigglypuff",
      "Wigglytuff",
      "Zubat",
      "Golbat",
      "Oddish",
      "Gloom",
      "Vileplume",
      "Paras",
      "Parasect",
      "Venonat",
      "Venomoth",
      "Diglett",
      "Dugtrio",
      "Meowth",
      "Persian",
      "Psyduck",
      "Golduck",
      "Mankey",
      "Primeape",
      "Growlithe",
      "Arcanine",
      "Poliwag",
      "Poliwhirl",
      "Poliwrath",
      "Abra",
      "Kadabra",
      "Alakazam",
      "Machop",
      "Machoke",
      "Machamp",
      "Bellsprout",
      "Weepinbell",
      "Victreebel",
      "Tentacool",
      "Tentacruel",
      "Geodude",
      "Graveler",
      "Golem",
      "Ponyta",
      "Rapidash",
      "Slowpoke",
      "Slowbro",
      "Magnemite",
      "Magneton",
      "Farfetch'd",
      "Doduo",
      "Dodrio",
      "Seel",
      "Dewgong",
      "Grimer",
      "Muk",
      "Shellder",
      "Cloyster",
      "Gastly",
      "Haunter",
      "Gengar",
      "Onix",
      "Drowzee",
      "Hypno",
      "Krabby",
      "Kingler",
      "Voltorb",
      "Electrode",
      "Exeggcute",
      "Exeggutor",
      "Cubone",
      "Marowak",
      "Hitmonlee",
      "Hitmonchan",
      "Lickitung",
      "Koffing",
      "Weezing",
      "Rhyhorn",
      "Rhydon",
      "Chansey",
      "Tangela",
      "Kangaskhan",
      "Horsea",
      "Seadra",
      "Goldeen",
      "Seaking",
      "Staryu",
      "Starmie",
      "Mr. Mime",
      "Scyther",
      "Jynx",
      "Electabuzz",
      "Magmar",
      "Pinsir",
      "Tauros",
      "Magikarp",
      "Gyarados",
      "Lapras",
      "Ditto",
      "Eevee",
      "Vaporeon",
      "Jolteon",
      "Flareon",
      "Porygon",
      "Omanyte",
      "Omastar",
      "Kabuto",
      "Kabutops",
      "Aerodactyl",
      "Snorlax",
      "Articuno",
      "Zapdos",
      "Moltres",
      "Dratini",
      "Dragonair",
      "Dragonite",
      "Mewtwo",
      "Mew",
    ],
  },
  {
    key: "pokemons2",
    emoji: "🌿",
    name: "Pokémons 2ª geração (Johto)",
    background: "#90EE90",
    image: require("@/assets/images/modules/pokemons2.png"),
    items: [
      "Chikorita",
      "Bayleef",
      "Meganium",
      "Cyndaquil",
      "Quilava",
      "Typhlosion",
      "Totodile",
      "Croconaw",
      "Feraligatr",
      "Sentret",
      "Furret",
      "Hoothoot",
      "Noctowl",
      "Ledyba",
      "Ledian",
      "Spinarak",
      "Ariados",
      "Crobat",
      "Chinchou",
      "Lanturn",
      "Pichu",
      "Cleffa",
      "Igglybuff",
      "Togepi",
      "Togetic",
      "Natu",
      "Xatu",
      "Mareep",
      "Flaaffy",
      "Ampharos",
      "Bellossom",
      "Marill",
      "Azumarill",
      "Sudowoodo",
      "Politoed",
      "Hoppip",
      "Skiploom",
      "Jumpluff",
      "Aipom",
      "Sunkern",
      "Sunflora",
      "Yanma",
      "Wooper",
      "Quagsire",
      "Espeon",
      "Umbreon",
      "Murkrow",
      "Slowking",
      "Misdreavus",
      "Unown",
      "Wobbuffet",
      "Girafarig",
      "Pineco",
      "Forretress",
      "Dunsparce",
      "Gligar",
      "Steelix",
      "Snubbull",
      "Granbull",
      "Qwilfish",
      "Scizor",
      "Shuckle",
      "Heracross",
      "Sneasel",
      "Teddiursa",
      "Ursaring",
      "Slugma",
      "Magcargo",
      "Swinub",
      "Piloswine",
      "Corsola",
      "Remoraid",
      "Octillery",
      "Delibird",
      "Mantine",
      "Skarmory",
      "Houndour",
      "Houndoom",
      "Kingdra",
      "Phanpy",
      "Donphan",
      "Porygon2",
      "Stantler",
      "Smeargle",
      "Tyrogue",
      "Hitmontop",
      "Smoochum",
      "Elekid",
      "Magby",
      "Miltank",
      "Blissey",
      "Raikou",
      "Entei",
      "Suicune",
      "Larvitar",
      "Pupitar",
      "Tyranitar",
      "Lugia",
      "Ho-Oh",
      "Celebi",
    ],
  },
  {
    key: "pokemons3",
    emoji: "🔥",
    name: "Pokémons 3ª geração (Hoenn)",
    background: "#FF4500",
    image: require("@/assets/images/modules/pokemons3.png"),
    items: [
      "Treecko",
      "Grovyle",
      "Sceptile",
      "Torchic",
      "Combusken",
      "Blaziken",
      "Mudkip",
      "Marshtomp",
      "Swampert",
      "Poochyena",
      "Mightyena",
      "Zigzagoon",
      "Linoone",
      "Wurmple",
      "Silcoon",
      "Beautifly",
      "Cascoon",
      "Dustox",
      "Lotad",
      "Lombre",
      "Ludicolo",
      "Seedot",
      "Nuzleaf",
      "Shiftry",
      "Taillow",
      "Swellow",
      "Wingull",
      "Pelipper",
      "Ralts",
      "Kirlia",
      "Gardevoir",
      "Surskit",
      "Masquerain",
      "Shroomish",
      "Breloom",
      "Slakoth",
      "Vigoroth",
      "Slaking",
      "Nincada",
      "Ninjask",
      "Shedinja",
      "Whismur",
      "Loudred",
      "Exploud",
      "Makuhita",
      "Hariyama",
      "Azurill",
      "Nosepass",
      "Skitty",
      "Delcatty",
      "Sableye",
      "Mawile",
      "Aron",
      "Lairon",
      "Aggron",
      "Meditite",
      "Medicham",
      "Electrike",
      "Manectric",
      "Plusle",
      "Minun",
      "Volbeat",
      "Illumise",
      "Roselia",
      "Gulpin",
      "Swalot",
      "Carvanha",
      "Sharpedo",
      "Wailmer",
      "Wailord",
      "Numel",
      "Camerupt",
      "Torkoal",
      "Spoink",
      "Grumpig",
      "Spinda",
      "Trapinch",
      "Vibrava",
      "Flygon",
      "Cacnea",
      "Cacturne",
      "Swablu",
      "Altaria",
      "Zangoose",
      "Seviper",
      "Lunatone",
      "Solrock",
      "Barboach",
      "Whiscash",
      "Corphish",
      "Crawdaunt",
      "Baltoy",
      "Claydol",
      "Lileep",
      "Cradily",
      "Anorith",
      "Armaldo",
      "Feebas",
      "Milotic",
      "Castform",
      "Kecleon",
      "Shuppet",
      "Banette",
      "Duskull",
      "Dusclops",
      "Tropius",
      "Chimecho",
      "Absol",
      "Wynaut",
      "Snorunt",
      "Glalie",
      "Spheal",
      "Sealeo",
      "Walrein",
      "Clamperl",
      "Huntail",
      "Gorebyss",
      "Relicanth",
      "Luvdisc",
      "Bagon",
      "Shelgon",
      "Salamence",
      "Beldum",
      "Metang",
      "Metagross",
      "Regirock",
      "Regice",
      "Registeel",
      "Latias",
      "Latios",
      "Kyogre",
      "Groudon",
      "Rayquaza",
      "Jirachi",
      "Deoxys",
    ],
  },
  {
    key: "pokemons4",
    emoji: "🌊",
    name: "Pokémons 4ª geração (Sinnoh)",
    background: "#ADD8E6",
    image: require("@/assets/images/modules/pokemons4.png"),
    items: [
      "Turtwig",
      "Grotle",
      "Torterra",
      "Chimchar",
      "Monferno",
      "Infernape",
      "Piplup",
      "Prinplup",
      "Empoleon",
      "Starly",
      "Staravia",
      "Staraptor",
      "Bidoof",
      "Bibarel",
      "Kricketot",
      "Kricketune",
      "Shinx",
      "Luxio",
      "Luxray",
      "Budew",
      "Roserade",
      "Cranidos",
      "Rampardos",
      "Shieldon",
      "Bastiodon",
      "Burmy",
      "Wormadam",
      "Mothim",
      "Combee",
      "Vespiquen",
      "Pachirisu",
      "Buizel",
      "Floatzel",
      "Cherubi",
      "Cherrim",
      "Shellos",
      "Gastrodon",
      "Ambipom",
      "Drifloon",
      "Drifblim",
      "Buneary",
      "Lopunny",
      "Mismagius",
      "Honchkrow",
      "Glameow",
      "Purugly",
      "Chingling",
      "Stunky",
      "Skuntank",
      "Bronzor",
      "Bronzong",
      "Bonsly",
      "Mime Jr.",
      "Happiny",
      "Chatot",
      "Spiritomb",
      "Gible",
      "Gabite",
      "Garchomp",
      "Munchlax",
      "Riolu",
      "Lucario",
      "Hippopotas",
      "Hippowdon",
      "Skorupi",
      "Drapion",
      "Croagunk",
      "Toxicroak",
      "Carnivine",
      "Finneon",
      "Lumineon",
      "Mantyke",
      "Snover",
      "Abomasnow",
      "Weavile",
      "Magnezone",
      "Lickilicky",
      "Rhyperior",
      "Tangrowth",
      "Electivire",
      "Magmortar",
      "Togekiss",
      "Yanmega",
      "Leafeon",
      "Glaceon",
      "Gliscor",
      "Mamoswine",
      "Porygon-Z",
      "Gallade",
      "Probopass",
      "Dusknoir",
      "Froslass",
      "Rotom",
      "Uxie",
      "Mesprit",
      "Azelf",
      "Dialga",
      "Palkia",
      "Heatran",
      "Regigigas",
      "Giratina",
      "Cresselia",
      "Phione",
      "Manaphy",
      "Darkrai",
      "Shaymin",
      "Arceus",
    ],
  },
  {
    key: "pokemons5",
    emoji: "🌍",
    name: "Pokémons 5ª geração (Unova)",
    background: "#32CD32",
    image: require("@/assets/images/modules/pokemons5.png"),
    items: [
      "Snivy",
      "Servine",
      "Serperior",
      "Tepig",
      "Pignite",
      "Emboar",
      "Oshawott",
      "Dewott",
      "Samurott",
      "Patrat",
      "Watchog",
      "Lillipup",
      "Herdier",
      "Stoutland",
      "Purrloin",
      "Liepard",
      "Pansage",
      "Simisage",
      "Pansear",
      "Simisear",
      "Panpour",
      "Simipour",
      "Munna",
      "Musharna",
      "Pidove",
      "Tranquill",
      "Unfezant",
      "Blitzle",
      "Zebstrika",
      "Roggenrola",
      "Boldore",
      "Gigalith",
      "Woobat",
      "Swoobat",
      "Drilbur",
      "Excadrill",
      "Audino",
      "Timburr",
      "Gurdurr",
      "Conkeldurr",
      "Tympole",
      "Palpitoad",
      "Seismitoad",
      "Throh",
      "Sawk",
      "Sewaddle",
      "Swadloon",
      "Leavanny",
      "Venipede",
      "Whirlipede",
      "Scolipede",
      "Cottonee",
      "Whimsicott",
      "Petilil",
      "Lilligant",
      "Sandile",
      "Krokorok",
      "Krookodile",
      "Darumaka",
      "Darmanitan",
      "Maractus",
      "Dwebble",
      "Crustle",
      "Scraggy",
      "Scrafty",
      "Sigilyph",
      "Yamask",
      "Cofagrigus",
      "Tirtouga",
      "Carracosta",
      "Archen",
      "Archeops",
      "Trubbish",
      "Garbodor",
      "Zorua",
      "Zoroark",
      "Minccino",
      "Cinccino",
      "Gothita",
      "Gothorita",
      "Gothitelle",
      "Solosis",
      "Duosion",
      "Reuniclus",
      "Ducklett",
      "Swanna",
      "Vanillite",
      "Vanillish",
      "Vanilluxe",
      "Deerling",
      "Sawsbuck",
      "Emolga",
      "Karrablast",
      "Escavalier",
      "Foongus",
      "Amoonguss",
      "Frillish",
      "Jellicent",
      "Alomomola",
      "Joltik",
      "Galvantula",
      "Ferroseed",
      "Ferrothorn",
      "Klink",
      "Klang",
      "Klinklang",
      "Tynamo",
      "Eelektrik",
      "Eelektross",
      "Elgyem",
      "Beheeyem",
      "Litwick",
      "Lampent",
      "Chandelure",
      "Axew",
      "Fraxure",
      "Haxorus",
      "Cubchoo",
      "Beartic",
      "Cryogonal",
      "Shelmet",
      "Accelgor",
      "Stunfisk",
      "Mienfoo",
      "Mienshao",
      "Druddigon",
      "Golett",
      "Golurk",
      "Pawniard",
      "Bisharp",
      "Bouffalant",
      "Rufflet",
      "Braviary",
      "Vullaby",
      "Mandibuzz",
      "Heatmor",
      "Durant",
      "Deino",
      "Zweilous",
      "Hydreigon",
      "Larvesta",
      "Volcarona",
      "Cobalion",
      "Terrakion",
      "Virizion",
      "Tornadus",
      "Thundurus",
      "Reshiram",
      "Zekrom",
      "Landorus",
      "Kyurem",
      "Keldeo",
      "Meloetta",
      "Genesect",
    ],
  },
  {
    key: "pokemons6",
    emoji: "🌟",
    name: "Pokémons 6ª geração (Kalos)",
    background: "#FFD700",
    image: require("@/assets/images/modules/pokemons6.png"),
    items: [
      "Chespin",
      "Quilladin",
      "Chesnaught",
      "Fennekin",
      "Braixen",
      "Delphox",
      "Froakie",
      "Frogadier",
      "Greninja",
      "Bunnelby",
      "Diggersby",
      "Fletchling",
      "Fletchinder",
      "Talonflame",
      "Scatterbug",
      "Spewpa",
      "Vivillon",
      "Litleo",
      "Pyroar",
      "Flabébé",
      "Floette",
      "Florges",
      "Skiddo",
      "Gogoat",
      "Pancham",
      "Pangoro",
      "Furfrou",
      "Espurr",
      "Meowstic",
      "Honedge",
      "Doublade",
      "Aegislash",
      "Spritzee",
      "Aromatisse",
      "Swirlix",
      "Slurpuff",
      "Inkay",
      "Malamar",
      "Binacle",
      "Barbaracle",
      "Skrelp",
      "Dragalge",
      "Clauncher",
      "Clawitzer",
      "Helioptile",
      "Heliolisk",
      "Tyrunt",
      "Tyrantrum",
      "Amaura",
      "Aurorus",
      "Sylveon",
      "Hawlucha",
      "Dedenne",
      "Carbink",
      "Goomy",
      "Sliggoo",
      "Goodra",
      "Klefki",
      "Phantump",
      "Trevenant",
      "Pumpkaboo",
      "Gourgeist",
      "Bergmite",
      "Avalugg",
      "Noibat",
      "Noivern",
      "Xerneas",
      "Yveltal",
      "Zygarde",
      "Diancie",
      "Hoopa",
      "Volcanion",
    ],
  },
  {
    key: "pokemons7",
    emoji: "🌺",
    name: "Pokémons 7ª geração (Alola)",
    background: "#FFB6C1",
    image: require("@/assets/images/modules/pokemons7.png"),
    items: [
      "Rowlet",
      "Dartrix",
      "Decidueye",
      "Litten",
      "Torracat",
      "Incineroar",
      "Popplio",
      "Brionne",
      "Primarina",
      "Pikipek",
      "Trumbeak",
      "Toucannon",
      "Yungoos",
      "Gumshoos",
      "Grubbin",
      "Charjabug",
      "Vikavolt",
      "Crabrawler",
      "Crabominable",
      "Oricorio",
      "Cutiefly",
      "Ribombee",
      "Rockruff",
      "Lycanroc",
      "Wishiwashi",
      "Mareanie",
      "Toxapex",
      "Mudbray",
      "Mudsdale",
      "Dewpider",
      "Araquanid",
      "Fomantis",
      "Lurantis",
      "Morelull",
      "Shiinotic",
      "Salandit",
      "Salazzle",
      "Stufful",
      "Bewear",
      "Bounsweet",
      "Steenee",
      "Tsareena",
      "Comfey",
      "Oranguru",
      "Passimian",
      "Wimpod",
      "Golisopod",
      "Sandygast",
      "Palossand",
      "Pyukumuku",
      "Type: Null",
      "Silvally",
      "Minior",
      "Komala",
      "Turtonator",
      "Togedemaru",
      "Mimikyu",
      "Bruxish",
      "Drampa",
      "Dhelmise",
      "Jangmo-o",
      "Hakamo-o",
      "Kommo-o",
      "Tapu Koko",
      "Tapu Lele",
      "Tapu Bulu",
      "Tapu Fini",
      "Cosmog",
      "Cosmoem",
      "Solgaleo",
      "Lunala",
      "Nihilego",
      "Buzzwole",
      "Pheromosa",
      "Xurkitree",
      "Celesteela",
      "Kartana",
      "Guzzlord",
      "Necrozma",
      "Magearna",
      "Marshadow",
      "Poipole",
      "Naganadel",
      "Stakataka",
      "Blacephalon",
      "Zeraora",
      "Meltan",
      "Melmetal",
    ],
  },
  {
    key: "pokemons8",
    emoji: "🔥",
    name: "Pokémons 8ª geração (Galar)",
    background: "#FF8C00",
    image: require("@/assets/images/modules/pokemons8.png"),
    items: [
      // Iniciais e evoluções
      "Grookey",
      "Thwackey",
      "Rillaboom",
      "Scorbunny",
      "Raboot",
      "Cinderace",
      "Sobble",
      "Drizzile",
      "Inteleon",

      // Linha Gossifleur
      "Gossifleur",
      "Eldegoss",

      // Linha Wooloo
      "Wooloo",
      "Dubwool",

      // Linha Chewtle
      "Chewtle",
      "Drednaw",

      // Linha Yamper
      "Yamper",
      "Boltund",

      // Linha Rolycoly
      "Rolycoly",
      "Carkol",
      "Coalossal",

      // Linha Applin
      "Applin",
      "Flapple",
      "Appletun",

      // Linha Silicobra
      "Silicobra",
      "Sandaconda",

      // Linha Cramorant
      "Cramorant",

      // Linha Arrokuda
      "Arrokuda",
      "Barraskewda",

      // Linha Toxel
      "Toxel",
      "Toxtricity",

      // Linha Sizzlipede
      "Sizzlipede",
      "Centiskorch",

      // Linha Clobbopus
      "Clobbopus",
      "Grapploct",

      // Linha Sinistea
      "Sinistea",
      "Polteageist",

      // Linha Hatenna
      "Hatenna",
      "Hattrem",
      "Hatterene",

      // Linha Impidimp
      "Impidimp",
      "Morgrem",
      "Grimmsnarl",

      // Linha Obstagoon
      "Zigzagoon (Galar)",
      "Linoone (Galar)",
      "Obstagoon",

      // Linha Perrserker
      "Meowth (Galar)",
      "Perrserker",

      // Linha Cursola
      "Corsola (Galar)",
      "Cursola",

      // Linha Sirfetch’d
      "Farfetch’d (Galar)",
      "Sirfetch’d",

      // Linha Mr. Rime
      "Mr. Mime (Galar)",
      "Mr. Rime",

      // Outros
      "Runerigus",
      "Falinks",
      "Pincurchin",
      "Snom",
      "Frosmoth",
      "Stonjourner",
      "Eiscue",
      "Indeedee",
      "Morpeko",
      "Cufant",
      "Copperajah",

      // Fosséis
      "Dracozolt",
      "Arctozolt",
      "Dracovish",
      "Arctovish",

      // Dragões e Lendários
      "Duraludon",
      "Dreepy",
      "Drakloak",
      "Dragapult",
      "Zacian",
      "Zamazenta",
      "Eternatus",
    ],
  },
  {
    key: "pokemons9",
    emoji: "🌈",
    name: "Pokémons 9ª geração (Paldea)",
    background: "#FF69B4",
    image: require("@/assets/images/modules/pokemons9.png"),
    items: [
      "Sprigatito",
      "Floragato",
      "Meowscarada",
      "Fuecoco",
      "Crocalor",
      "Skeledirge",
      "Quaxly",
      "Quaxwell",
      "Quaquaval",
      "Lechonk",
      "Oinkologne",
      "Tarountula",
      "Spidops",
      "Nymble",
      "Lokix",
      "Pawmi",
      "Pawmo",
      "Pawmot",
      "Tandemaus",
      "Maushold",
      "Fidough",
      "Dachsbun",
      "Smoliv",
      "Dolliv",
      "Arboliva",
      "Squawkabilly",
      "Nacli",
      "Naclstack",
      "Garganacl",
      "Charcadet",
      "Armarouge",
      "Ceruledge",
      "Tadbulb",
      "Bellibolt",
      "Wattrel",
      "Kilowattrel",
      "Maschiff",
      "Mabosstiff",
      "Shroodle",
      "Grafaiai",
      "Bramblin",
      "Brambleghast",
      "Toedscool",
      "Toedscruel",
      "Klawf",
      "Capsakid",
      "Scovillain",
      "Rellor",
      "Rabsca",
      "Flittle",
      "Espathra",
      "Tinkatink",
      "Tinkatuff",
      "Tinkaton",
      "Wiglett",
      "Wugtrio",
      "Bombirdier",
      "Finizen",
      "Palafin",
      "Varoom",
      "Revavroom",
      "Cyclizar",
      "Orthworm",
      "Glimmet",
      "Glimmora",
      "Greavard",
      "Houndstone",
      "Flamigo",
      "Cetoddle",
      "Cetitan",
      "Veluza",
      "Dondozo",
      "Tatsugiri",
      "Annihilape",
      "Clodsire",
      "Farigiraf",
      "Dudunsparce",
      "Kingambit",
      "Great Tusk",
      "Scream Tail",
      "Brute Bonnet",
      "Flutter Mane",
      "Slither Wing",
      "Sandy Shocks",
      "Iron Treads",
      "Iron Bundle",
      "Iron Hands",
      "Iron Jugulis",
      "Iron Moth",
      "Iron Thorns",
      "Frigibax",
      "Arctibax",
      "Baxcalibur",
      "Gimmighoul",
      "Gholdengo",
      "Wo-Chien",
      "Chien-Pao",
      "Ting-Lu",
      "Chi-Yu",
      "Roaring Moon",
      "Iron Valiant",
      "Koraidon",
      "Miraidon",
    ],
  },
];

export function useCategoryOptions(category: string) {
  const [options, setOptions] = useState(
    categories.find((c) => c.key === category).items
  );
  const [usedOptions, setUsedOptions] = useState<string[]>([]);

  const getNextOption = (): string | null => {
    if (options.length === 0) {
      return null;
    }

    const randomIndex = Math.floor(Math.random() * options.length);
    const nextOption = options[randomIndex];

    setOptions((prev) => prev.filter((_, index) => index !== randomIndex));
    setUsedOptions((prev) => [...prev, nextOption]);

    return nextOption;
  };

  const resetRound = () => {
    setOptions([...categories.find((c) => c.key === category).items]);
    setUsedOptions([]);
  };

  return {
    options,
    usedOptions,
    getNextOption,
    resetRound,
  };
}
